// Curated technology catalog for product profiles. `icon` is a simple-icons slug (https://cdn.simpleicons.org/<slug>);
// entries without one render as a plain chip. Founders may also add free-text entries (stored lowercased, no icon).
export type StackGroup = "Frontend" | "Backend" | "Database" | "Auth" | "Payments" | "Hosting" | "Analytics" | "Messaging" | "AI" | "Mobile" | "Tooling" | "Other";

export const TECH_STACK: { slug: string; label: string; icon?: string; group: StackGroup }[] = [
  // Frontend
  { slug: "react", label: "React", icon: "react", group: "Frontend" },
  { slug: "nextjs", label: "Next.js", icon: "nextdotjs", group: "Frontend" },
  { slug: "vue", label: "Vue", icon: "vuedotjs", group: "Frontend" },
  { slug: "nuxt", label: "Nuxt", icon: "nuxt", group: "Frontend" },
  { slug: "svelte", label: "Svelte", icon: "svelte", group: "Frontend" },
  { slug: "angular", label: "Angular", icon: "angular", group: "Frontend" },
  { slug: "remix", label: "Remix", icon: "remix", group: "Frontend" },
  { slug: "astro", label: "Astro", icon: "astro", group: "Frontend" },
  { slug: "solid", label: "SolidJS", icon: "solid", group: "Frontend" },
  { slug: "qwik", label: "Qwik", icon: "qwik", group: "Frontend" },
  { slug: "htmx", label: "htmx", icon: "htmx", group: "Frontend" },
  { slug: "alpinejs", label: "Alpine.js", icon: "alpinedotjs", group: "Frontend" },
  { slug: "tailwind", label: "Tailwind CSS", icon: "tailwindcss", group: "Frontend" },
  { slug: "shadcn", label: "shadcn/ui", icon: "shadcnui", group: "Frontend" },
  { slug: "bootstrap", label: "Bootstrap", icon: "bootstrap", group: "Frontend" },
  { slug: "mui", label: "MUI", icon: "mui", group: "Frontend" },
  { slug: "chakra", label: "Chakra UI", icon: "chakraui", group: "Frontend" },
  { slug: "radix", label: "Radix UI", icon: "radixui", group: "Frontend" },
  { slug: "threejs", label: "Three.js", icon: "threedotjs", group: "Frontend" },
  { slug: "typescript", label: "TypeScript", icon: "typescript", group: "Frontend" },
  { slug: "javascript", label: "JavaScript", icon: "javascript", group: "Frontend" },
  // Backend
  { slug: "nodejs", label: "Node.js", icon: "nodedotjs", group: "Backend" },
  { slug: "bun", label: "Bun", icon: "bun", group: "Backend" },
  { slug: "deno", label: "Deno", icon: "deno", group: "Backend" },
  { slug: "express", label: "Express", icon: "express", group: "Backend" },
  { slug: "nestjs", label: "NestJS", icon: "nestjs", group: "Backend" },
  { slug: "hono", label: "Hono", icon: "hono", group: "Backend" },
  { slug: "fastify", label: "Fastify", icon: "fastify", group: "Backend" },
  { slug: "trpc", label: "tRPC", icon: "trpc", group: "Backend" },
  { slug: "graphql", label: "GraphQL", icon: "graphql", group: "Backend" },
  { slug: "python", label: "Python", icon: "python", group: "Backend" },
  { slug: "django", label: "Django", icon: "django", group: "Backend" },
  { slug: "flask", label: "Flask", icon: "flask", group: "Backend" },
  { slug: "fastapi", label: "FastAPI", icon: "fastapi", group: "Backend" },
  { slug: "ruby", label: "Ruby", icon: "ruby", group: "Backend" },
  { slug: "rails", label: "Ruby on Rails", icon: "rubyonrails", group: "Backend" },
  { slug: "php", label: "PHP", icon: "php", group: "Backend" },
  { slug: "laravel", label: "Laravel", icon: "laravel", group: "Backend" },
  { slug: "go", label: "Go", icon: "go", group: "Backend" },
  { slug: "rust", label: "Rust", icon: "rust", group: "Backend" },
  { slug: "elixir", label: "Elixir", icon: "elixir", group: "Backend" },
  { slug: "phoenix", label: "Phoenix", icon: "phoenixframework", group: "Backend" },
  { slug: "java", label: "Java / Spring", icon: "spring", group: "Backend" },
  { slug: "dotnet", label: ".NET", icon: "dotnet", group: "Backend" },
  { slug: "kotlin", label: "Kotlin", icon: "kotlin", group: "Backend" },
  // Database
  { slug: "postgresql", label: "PostgreSQL", icon: "postgresql", group: "Database" },
  { slug: "mysql", label: "MySQL", icon: "mysql", group: "Database" },
  { slug: "mariadb", label: "MariaDB", icon: "mariadb", group: "Database" },
  { slug: "mongodb", label: "MongoDB", icon: "mongodb", group: "Database" },
  { slug: "redis", label: "Redis", icon: "redis", group: "Database" },
  { slug: "sqlite", label: "SQLite", icon: "sqlite", group: "Database" },
  { slug: "supabase", label: "Supabase", icon: "supabase", group: "Database" },
  { slug: "firebase", label: "Firebase", icon: "firebase", group: "Database" },
  { slug: "convex", label: "Convex", icon: "convex", group: "Database" },
  { slug: "neon", label: "Neon", icon: "neon", group: "Database" },
  { slug: "planetscale", label: "PlanetScale", icon: "planetscale", group: "Database" },
  { slug: "turso", label: "Turso", icon: "turso", group: "Database" },
  { slug: "upstash", label: "Upstash", icon: "upstash", group: "Database" },
  { slug: "prisma", label: "Prisma", icon: "prisma", group: "Database" },
  { slug: "drizzle", label: "Drizzle", icon: "drizzle", group: "Database" },
  { slug: "clickhouse", label: "ClickHouse", icon: "clickhouse", group: "Database" },
  { slug: "elasticsearch", label: "Elasticsearch", icon: "elasticsearch", group: "Database" },
  { slug: "appwrite", label: "Appwrite", icon: "appwrite", group: "Database" },
  { slug: "pocketbase", label: "PocketBase", icon: "pocketbase", group: "Database" },
  { slug: "hasura", label: "Hasura", icon: "hasura", group: "Database" },
  // Auth
  { slug: "clerk", label: "Clerk", icon: "clerk", group: "Auth" },
  { slug: "betterauth", label: "Better Auth", icon: "betterauth", group: "Auth" },
  { slug: "auth0", label: "Auth0", icon: "auth0", group: "Auth" },
  { slug: "authjs", label: "Auth.js / NextAuth", group: "Auth" },
  { slug: "lucia", label: "Lucia", icon: "lucia", group: "Auth" },
  { slug: "kinde", label: "Kinde", group: "Auth" },
  { slug: "workos", label: "WorkOS", group: "Auth" },
  { slug: "keycloak", label: "Keycloak", icon: "keycloak", group: "Auth" },
  { slug: "okta", label: "Okta", icon: "okta", group: "Auth" },
  // Payments (conversion state only — UserTrack never reads amounts)
  { slug: "stripe", label: "Stripe", icon: "stripe", group: "Payments" },
  { slug: "paddle", label: "Paddle", icon: "paddle", group: "Payments" },
  { slug: "lemonsqueezy", label: "Lemon Squeezy", icon: "lemonsqueezy", group: "Payments" },
  { slug: "revenuecat", label: "RevenueCat", icon: "revenuecat", group: "Payments" },
  { slug: "chargebee", label: "Chargebee", group: "Payments" },
  { slug: "paypal", label: "PayPal", icon: "paypal", group: "Payments" },
  { slug: "gumroad", label: "Gumroad", icon: "gumroad", group: "Payments" },
  { slug: "polar", label: "Polar", group: "Payments" },
  // Hosting
  { slug: "vercel", label: "Vercel", icon: "vercel", group: "Hosting" },
  { slug: "railway", label: "Railway", icon: "railway", group: "Hosting" },
  { slug: "render", label: "Render", icon: "render", group: "Hosting" },
  { slug: "flyio", label: "Fly.io", icon: "flydotio", group: "Hosting" },
  { slug: "netlify", label: "Netlify", icon: "netlify", group: "Hosting" },
  { slug: "aws", label: "AWS", group: "Hosting" },
  { slug: "gcp", label: "Google Cloud", icon: "googlecloud", group: "Hosting" },
  { slug: "azure", label: "Azure", group: "Hosting" },
  { slug: "cloudflare", label: "Cloudflare", icon: "cloudflare", group: "Hosting" },
  { slug: "digitalocean", label: "DigitalOcean", icon: "digitalocean", group: "Hosting" },
  { slug: "hetzner", label: "Hetzner", icon: "hetzner", group: "Hosting" },
  { slug: "heroku", label: "Heroku", group: "Hosting" },
  { slug: "docker", label: "Docker", icon: "docker", group: "Hosting" },
  { slug: "kubernetes", label: "Kubernetes", icon: "kubernetes", group: "Hosting" },
  { slug: "terraform", label: "Terraform", icon: "terraform", group: "Hosting" },
  { slug: "coolify", label: "Coolify", icon: "coolify", group: "Hosting" },
  { slug: "nginx", label: "NGINX", icon: "nginx", group: "Hosting" },
  // Analytics & monitoring
  { slug: "posthog", label: "PostHog", icon: "posthog", group: "Analytics" },
  { slug: "plausible", label: "Plausible", icon: "plausibleanalytics", group: "Analytics" },
  { slug: "ga4", label: "Google Analytics", icon: "googleanalytics", group: "Analytics" },
  { slug: "mixpanel", label: "Mixpanel", icon: "mixpanel", group: "Analytics" },
  { slug: "amplitude", label: "Amplitude", group: "Analytics" },
  { slug: "umami", label: "Umami", icon: "umami", group: "Analytics" },
  { slug: "fathom", label: "Fathom", icon: "fathom", group: "Analytics" },
  { slug: "matomo", label: "Matomo", icon: "matomo", group: "Analytics" },
  { slug: "rybbit", label: "Rybbit", group: "Analytics" },
  { slug: "hotjar", label: "Hotjar", icon: "hotjar", group: "Analytics" },
  { slug: "segment", label: "Segment", group: "Analytics" },
  { slug: "sentry", label: "Sentry", icon: "sentry", group: "Analytics" },
  { slug: "datadog", label: "Datadog", icon: "datadog", group: "Analytics" },
  { slug: "grafana", label: "Grafana", icon: "grafana", group: "Analytics" },
  // Email & messaging
  { slug: "resend", label: "Resend", icon: "resend", group: "Messaging" },
  { slug: "sendgrid", label: "SendGrid", group: "Messaging" },
  { slug: "postmark", label: "Postmark", group: "Messaging" },
  { slug: "mailgun", label: "Mailgun", icon: "mailgun", group: "Messaging" },
  { slug: "loops", label: "Loops", icon: "loops", group: "Messaging" },
  { slug: "mailchimp", label: "Mailchimp", icon: "mailchimp", group: "Messaging" },
  { slug: "brevo", label: "Brevo", icon: "brevo", group: "Messaging" },
  { slug: "customerio", label: "Customer.io", group: "Messaging" },
  { slug: "twilio", label: "Twilio", group: "Messaging" },
  { slug: "intercom", label: "Intercom", icon: "intercom", group: "Messaging" },
  { slug: "crisp", label: "Crisp", group: "Messaging" },
  { slug: "zendesk", label: "Zendesk", icon: "zendesk", group: "Messaging" },
  { slug: "slack", label: "Slack", group: "Messaging" },
  { slug: "discord", label: "Discord", icon: "discord", group: "Messaging" },
  { slug: "telegram", label: "Telegram", icon: "telegram", group: "Messaging" },
  // AI
  { slug: "openai", label: "OpenAI", group: "AI" },
  { slug: "anthropic", label: "Anthropic", icon: "anthropic", group: "AI" },
  { slug: "gemini", label: "Google Gemini", icon: "googlegemini", group: "AI" },
  { slug: "mistral", label: "Mistral", icon: "mistralai", group: "AI" },
  { slug: "huggingface", label: "Hugging Face", icon: "huggingface", group: "AI" },
  { slug: "replicate", label: "Replicate", icon: "replicate", group: "AI" },
  { slug: "ollama", label: "Ollama", icon: "ollama", group: "AI" },
  { slug: "langchain", label: "LangChain", icon: "langchain", group: "AI" },
  { slug: "pytorch", label: "PyTorch", icon: "pytorch", group: "AI" },
  { slug: "tensorflow", label: "TensorFlow", icon: "tensorflow", group: "AI" },
  { slug: "elevenlabs", label: "ElevenLabs", icon: "elevenlabs", group: "AI" },
  { slug: "pinecone", label: "Pinecone", group: "AI" },
  { slug: "qdrant", label: "Qdrant", icon: "qdrant", group: "AI" },
  // Mobile & desktop
  { slug: "reactnative", label: "React Native", icon: "react", group: "Mobile" },
  { slug: "expo", label: "Expo", icon: "expo", group: "Mobile" },
  { slug: "flutter", label: "Flutter", icon: "flutter", group: "Mobile" },
  { slug: "swift", label: "Swift", icon: "swift", group: "Mobile" },
  { slug: "capacitor", label: "Capacitor", icon: "capacitor", group: "Mobile" },
  { slug: "ionic", label: "Ionic", icon: "ionic", group: "Mobile" },
  { slug: "electron", label: "Electron", icon: "electron", group: "Mobile" },
  { slug: "tauri", label: "Tauri", icon: "tauri", group: "Mobile" },
  // Tooling
  { slug: "github", label: "GitHub", icon: "github", group: "Tooling" },
  { slug: "gitlab", label: "GitLab", icon: "gitlab", group: "Tooling" },
  { slug: "githubactions", label: "GitHub Actions", icon: "githubactions", group: "Tooling" },
  { slug: "vite", label: "Vite", icon: "vite", group: "Tooling" },
  { slug: "turborepo", label: "Turborepo", icon: "turborepo", group: "Tooling" },
  { slug: "pnpm", label: "pnpm", icon: "pnpm", group: "Tooling" },
  { slug: "storybook", label: "Storybook", icon: "storybook", group: "Tooling" },
  { slug: "vitest", label: "Vitest", icon: "vitest", group: "Tooling" },
  { slug: "jest", label: "Jest", icon: "jest", group: "Tooling" },
  { slug: "playwright", label: "Playwright", group: "Tooling" },
  { slug: "cypress", label: "Cypress", icon: "cypress", group: "Tooling" },
  { slug: "inngest", label: "Inngest", group: "Tooling" },
  { slug: "zapier", label: "Zapier", icon: "zapier", group: "Tooling" },
  { slug: "n8n", label: "n8n", icon: "n8n", group: "Tooling" },
  { slug: "make", label: "Make", icon: "make", group: "Tooling" },
  // Other
  { slug: "airtable", label: "Airtable", icon: "airtable", group: "Other" },
  { slug: "notion", label: "Notion", icon: "notion", group: "Other" },
  { slug: "linear", label: "Linear", icon: "linear", group: "Other" },
  { slug: "figma", label: "Figma", icon: "figma", group: "Other" },
  { slug: "framer", label: "Framer", icon: "framer", group: "Other" },
  { slug: "webflow", label: "Webflow", icon: "webflow", group: "Other" },
  { slug: "wordpress", label: "WordPress", icon: "wordpress", group: "Other" },
  { slug: "shopify", label: "Shopify", icon: "shopify", group: "Other" },
  { slug: "hubspot", label: "HubSpot", icon: "hubspot", group: "Other" },
  { slug: "salesforce", label: "Salesforce", icon: "salesforce", group: "Other" },
  { slug: "algolia", label: "Algolia", icon: "algolia", group: "Other" },
  { slug: "meilisearch", label: "Meilisearch", icon: "meilisearch", group: "Other" },
  { slug: "strapi", label: "Strapi", icon: "strapi", group: "Other" },
  { slug: "sanity", label: "Sanity", icon: "sanity", group: "Other" },
  { slug: "contentful", label: "Contentful", icon: "contentful", group: "Other" },
  { slug: "payload", label: "Payload CMS", icon: "payloadcms", group: "Other" },
  { slug: "cloudinary", label: "Cloudinary", icon: "cloudinary", group: "Other" },
  { slug: "mapbox", label: "Mapbox", icon: "mapbox", group: "Other" },
  { slug: "socketio", label: "Socket.IO", icon: "socketdotio", group: "Other" },
  { slug: "pusher", label: "Pusher", icon: "pusher", group: "Other" },
  { slug: "kafka", label: "Apache Kafka", icon: "apachekafka", group: "Other" },
  { slug: "rabbitmq", label: "RabbitMQ", icon: "rabbitmq", group: "Other" },
  { slug: "calcom", label: "Cal.com", icon: "caldotcom", group: "Other" },
  { slug: "typeform", label: "Typeform", icon: "typeform", group: "Other" },
  { slug: "unity", label: "Unity", icon: "unity", group: "Other" },
  { slug: "godot", label: "Godot", icon: "godotengine", group: "Other" },
];

export const TECH_STACK_MAX = 20;
export const TECH_STACK_BY_SLUG = new Map(TECH_STACK.map((t) => [t.slug, t]));
export const techLabel = (slug: string) => TECH_STACK_BY_SLUG.get(slug)?.label ?? slug;
export const techIconUrl = (slug: string) => { const icon = TECH_STACK_BY_SLUG.get(slug)?.icon; return icon ? `https://cdn.simpleicons.org/${icon}` : undefined; };

// Free-text entries: lowercase slug-ish token, 2–30 chars. Anything else is dropped.
export const normalizeStackEntry = (raw: string) => { const s = raw.trim().toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9.+#-]/g, ""); return s.length >= 2 && s.length <= 30 ? s : undefined; };
