// Agent-executable integration knowledge: catalog, recommendation and structured setup instructions.
// Pure data + functions, shared by the MCP server and the developer docs. No I/O.
import { COHORT_RULES, IDENTITY_QUALITY_META } from "./identity";
import { NATIVE_PACKAGE, NATIVE_SOURCE_LABEL, type NativeSource, nativeSetup } from "./nativeSetup";

export type ProviderKind = "clerk" | "supabase" | "firebase" | "native" | "auth0" | "posthog" | "plausible" | "ga4" | "stripe" | "revenuecat" | "paddle" | "lemonsqueezy" | "chargebee" | "postgres" | "endpoint" | "manual";
export type Role = "users" | "activation" | "traffic" | "conversion";
export type ProjectType = "web" | "mobile" | "hybrid";
export type ConversionMode = "active_paid" | "ever_paid" | "first_payment";
export type LifecycleStage = "reached" | "signed_up" | "activated" | "trial" | "converted";

export interface Credential {
  key: string;
  label: string;
  secret: boolean;
  optional?: boolean;
  roles?: Role[];
  whereToFind: string;
  envVarHints: string[];
  format?: string;
}

export interface CatalogEntry {
  provider: ProviderKind;
  label: string;
  roles: Role[];
  trust: "verified" | "conditional" | "unverified";
  summary: string;
  detects: string[];
  credentials: Credential[];
  permissions: string[];
  reads: string;
  neverSent: string[];
}

const NEVER = ["emails", "names", "passwords", "session tokens", "per-user records", "payment details"];
const NEVER_PAYMENTS = [...NEVER, "amounts", "prices", "invoices", "MRR / revenue"];
const MODE_CREDENTIAL: Credential = { key: "mode", label: "Converted means", secret: false, optional: true, whereToFind: "active_paid (default: currently has a paid subscription) | ever_paid (paid at least once) | first_payment (counted at the first successful payment). Provider-independent; change later without reconnecting.", envVarHints: [], format: "active_paid | ever_paid | first_payment" };

export const INTEGRATION_CATALOG: CatalogEntry[] = [
  {
    provider: "native",
    label: "My app (SDK)",
    roles: ["users", "activation", "conversion"],
    trust: "verified",
    summary: "Native, verified: your app answers signed aggregate requests itself (~2 min). Better Auth via the official plugin @usertrack/better-auth; Prisma, Drizzle, Convex, Auth.js / NextAuth or any custom app via @usertrack/node (one route + a count function). Users, and optionally activation + conversion, from one handler. No PII, no database credentials shared with UserTrack.",
    detects: ["better-auth", "@better-auth/core", "@better-auth/cli", "BETTER_AUTH_SECRET", "BETTER_AUTH_URL", "@convex-dev/better-auth", "next-auth", "@auth/core", "@auth/prisma-adapter", "@auth/drizzle-adapter", "AUTH_SECRET", "NEXTAUTH_SECRET", "convex", "@prisma/client", "prisma", "drizzle-orm", "drizzle-kit", "lucia", "kysely", "mongoose", "sequelize", "typeorm"],
    credentials: [
      { key: "source", label: "SDK adapter", secret: false, whereToFind: "better-auth (official plugin) | prisma | drizzle | convex | authjs | custom — pick from what you detected; custom works with any count function.", envVarHints: [], format: "better-auth | prisma | drizzle | convex | authjs | custom" },
      { key: "url", label: "Base URL", secret: false, whereToFind: "Better Auth: the public base URL of the Better Auth instance (baseURL + basePath, e.g. https://app.example.com/api/auth). Others: where the handler is mounted, e.g. https://app.example.com/api/usertrack (metrics at <base>/metrics); Convex: the deployment's .convex.site URL. Defaults to <websiteUrl>/api/auth or /api/usertrack.", envVarHints: ["BETTER_AUTH_URL", "NEXT_PUBLIC_APP_URL", "CONVEX_SITE_URL"], format: "https://…" },
      { key: "secret", label: "Integration secret", secret: true, whereToFind: "Generated by UserTrack when the integration is created (usertrack_create_integration or the dashboard); shown once. Put it into the app as USERTRACK_SECRET together with USERTRACK_PROJECT_ID.", envVarHints: ["USERTRACK_SECRET"], format: "ut_int_…" },
    ],
    permissions: ["No third-party credential is needed: the SDK runs inside the app and answers signed requests with aggregate counts only.", "The secret authenticates both directions (UserTrack → app pull, app → UserTrack events); rotate it from the dashboard or usertrack_create_integration { rotate: true }."],
    reads: "POST <base>/metrics (Better Auth: <base>/usertrack/metrics), HMAC-signed: users { totalUsers, newUsers 24h/7d/30d, daily ≤ 90 days }, optional activation { activatedUsers … } and conversion { convertedUsers, trialUsers, mode … }, optional identities (stable ids). Optional pushed events user.created / user.deleted / user.activated / trial.started / user.converted with a pseudonymous subject. Never user records.",
    neverSent: NEVER,
  },
  {
    provider: "clerk",
    label: "Clerk",
    roles: ["users"],
    trust: "verified",
    summary: "User count, signups and active users via the Clerk Backend API (count endpoint only).",
    detects: ["@clerk/nextjs", "@clerk/clerk-sdk-node", "@clerk/backend", "@clerk/clerk-react", "CLERK_SECRET_KEY"],
    credentials: [{ key: "secretKey", label: "Clerk secret key", secret: true, whereToFind: "Clerk Dashboard → Configure → API Keys → Secret key", envVarHints: ["CLERK_SECRET_KEY"], format: "sk_live_… or sk_test_…" }],
    permissions: ["Any Clerk secret key works; UserTrack only calls GET /v1/users/count."],
    reads: "GET /v1/users/count with created_at / last_active_at filters. Never lists users.",
    neverSent: NEVER,
  },
  {
    provider: "supabase",
    label: "Supabase",
    roles: ["users", "activation"],
    trust: "verified",
    summary: "Preferred: a read-only Postgres connection string → auth.users signups per day (24h/7d/30d + 30-day history). Fallback: project URL + service role key → total users only.",
    detects: ["@supabase/supabase-js", "@supabase/ssr", "@supabase/auth-helpers-nextjs", "SUPABASE_SERVICE_ROLE_KEY", "NEXT_PUBLIC_SUPABASE_URL", "SUPABASE_DB_URL"],
    credentials: [
      { key: "connectionString", label: "Read-only database connection string (preferred)", secret: true, optional: true, whereToFind: "Supabase → Connect → Session pooler (IPv4) → copy the URI; ideally for a dedicated read-only role (see steps). Unlocks verified signups per window and history. If given, url/serviceKey are not needed.", envVarHints: ["SUPABASE_DB_URL", "DATABASE_URL", "POSTGRES_URL"], format: "postgresql://postgres.<ref>:<password>@aws-0-<region>.pooler.supabase.com:5432/postgres" },
      { key: "url", label: "Project URL (fallback mode)", secret: false, optional: true, whereToFind: "Supabase → Project Settings → API → Project URL", envVarHints: ["NEXT_PUBLIC_SUPABASE_URL", "SUPABASE_URL"], format: "https://xxxx.supabase.co" },
      { key: "serviceKey", label: "Service role key (fallback mode)", secret: true, optional: true, whereToFind: "Supabase → Project Settings → API → service_role (server-only). Only counts auth.users; no per-window signups.", envVarHints: ["SUPABASE_SERVICE_ROLE_KEY", "SUPABASE_SERVICE_KEY"] },
      { key: "table", label: "Table to count", secret: false, optional: true, roles: ["users"], whereToFind: "Leave empty to count auth.users; otherwise a public table with one row per user (e.g. profiles).", envVarHints: [] },
      { key: "table", label: "Table with one row per activated user", secret: false, roles: ["activation"], whereToFind: "A table that only gets a row once a user really used the product (e.g. projects_owners).", envVarHints: [] },
      { key: "createdAtColumn", label: "created_at column", secret: false, optional: true, whereToFind: "Timestamp column on that table; unlocks 24h/7d/30d counts and 30-day history.", envVarHints: [] },
    ],
    permissions: ["Database mode: create a read-only role and grant SELECT on auth.users (or the activation table): CREATE ROLE usertrack_ro LOGIN PASSWORD '…'; GRANT USAGE ON SCHEMA auth TO usertrack_ro; GRANT SELECT ON auth.users TO usertrack_ro; — then use it in the pooler connection string.", "API mode: the service role key must stay server-side; UserTrack stores it encrypted and never returns it."],
    reads: "Database mode: SELECT count(*) … WHERE created_at >= $1 on auth.users (deleted_at IS NULL) plus one GROUP BY day query for history. API mode: HEAD count=exact / admin/users?per_page=1 — counts only, never row data.",
    neverSent: NEVER,
  },
  {
    provider: "firebase",
    label: "Firebase Auth",
    roles: ["users"],
    trust: "verified",
    summary: "Total users via the Identity Toolkit admin API (viewer-only service account). Signups per window + 30-day history via a createdAt scan for projects up to 100k accounts; larger projects use snapshot deltas.",
    detects: ["firebase", "firebase-admin", "@firebase/auth", "FIREBASE_PROJECT_ID", "GOOGLE_APPLICATION_CREDENTIALS"],
    credentials: [
      { key: "serviceAccount", label: "Service account JSON", secret: true, whereToFind: "Google Cloud Console → IAM & Admin → Service Accounts → create one with role 'Firebase Authentication Viewer' → Keys → Add key (JSON)", envVarHints: ["FIREBASE_SERVICE_ACCOUNT", "GOOGLE_APPLICATION_CREDENTIALS"], format: "Full JSON file contents" },
      { key: "projectId", label: "Project ID", secret: false, optional: true, whereToFind: "Firebase console → Project settings; taken from the JSON if empty", envVarHints: ["FIREBASE_PROJECT_ID", "NEXT_PUBLIC_FIREBASE_PROJECT_ID"] },
    ],
    permissions: ["Create a dedicated service account with only 'Firebase Authentication Viewer'. Do not reuse the admin SDK account."],
    reads: "accounts:query with returnUserInfo=false for the total; accounts:batchGet pages (≤100k) read only createdAt and are discarded immediately — nothing per-user is stored.",
    neverSent: NEVER,
  },
  {
    provider: "auth0",
    label: "Auth0",
    roles: ["users"],
    trust: "verified",
    summary: "Users, daily signups and active users via a Machine-to-Machine app with read scopes.",
    detects: ["@auth0/nextjs-auth0", "auth0", "@auth0/auth0-react", "AUTH0_DOMAIN", "AUTH0_CLIENT_ID"],
    credentials: [
      { key: "domain", label: "Tenant domain", secret: false, whereToFind: "Auth0 → Settings → Domain", envVarHints: ["AUTH0_DOMAIN", "AUTH0_ISSUER_BASE_URL"], format: "acme.eu.auth0.com" },
      { key: "clientId", label: "M2M client ID", secret: false, whereToFind: "Auth0 → Applications → (new Machine to Machine app) → Client ID", envVarHints: ["AUTH0_M2M_CLIENT_ID"] },
      { key: "clientSecret", label: "M2M client secret", secret: true, whereToFind: "Same application → Client Secret", envVarHints: ["AUTH0_M2M_CLIENT_SECRET"] },
    ],
    permissions: ["Create a new M2M application authorised for the Auth0 Management API with only read:users and read:stats."],
    reads: "GET /api/v2/users?include_totals (count only), /stats/daily, /stats/active-users.",
    neverSent: NEVER,
  },
  {
    provider: "posthog",
    label: "PostHog",
    roles: ["activation", "traffic"],
    trust: "verified",
    summary: "Activation events (distinct persons) and web traffic via HogQL aggregates.",
    detects: ["posthog-js", "posthog-node", "NEXT_PUBLIC_POSTHOG_KEY", "POSTHOG_API_KEY"],
    credentials: [
      { key: "host", label: "Host", secret: false, whereToFind: "https://us.posthog.com, https://eu.posthog.com or your self-hosted URL", envVarHints: ["NEXT_PUBLIC_POSTHOG_HOST", "POSTHOG_HOST"] },
      { key: "projectId", label: "Project ID", secret: false, whereToFind: "PostHog → Settings → Project → Project ID", envVarHints: ["POSTHOG_PROJECT_ID"] },
      { key: "apiKey", label: "Personal API key (query:read)", secret: true, whereToFind: "PostHog → Settings → Personal API keys → create with scope query:read", envVarHints: ["POSTHOG_PERSONAL_API_KEY"], format: "phx_…" },
      { key: "activationEvent", label: "Activation event", secret: false, roles: ["activation"], whereToFind: "The event name that means a user really started (e.g. project_created, onboarding_completed). Grep the repo for posthog.capture(...) calls.", envVarHints: [] },
    ],
    permissions: ["Personal API key with only query:read. The project (phc_) key is not enough and must not be used."],
    reads: "count(distinct person_id) HogQL queries. Aggregates only.",
    neverSent: NEVER,
  },
  {
    provider: "plausible",
    label: "Plausible",
    roles: ["traffic"],
    trust: "verified",
    summary: "Visitors and visits from the Plausible Stats API.",
    detects: ["plausible", "next-plausible", "PLAUSIBLE_API_KEY"],
    credentials: [
      { key: "siteId", label: "Site ID (domain)", secret: false, whereToFind: "Exactly as shown in Plausible", envVarHints: ["PLAUSIBLE_DOMAIN", "NEXT_PUBLIC_PLAUSIBLE_DOMAIN"] },
      { key: "apiKey", label: "API key", secret: true, whereToFind: "Plausible → Settings → API keys", envVarHints: ["PLAUSIBLE_API_KEY"] },
      { key: "host", label: "Host", secret: false, optional: true, whereToFind: "Self-hosted instance URL if any", envVarHints: ["PLAUSIBLE_HOST"] },
    ],
    permissions: ["Stats API key (read-only by design)."],
    reads: "stats/aggregate and stats/timeseries — visitor counts only.",
    neverSent: NEVER,
  },
  {
    provider: "ga4",
    label: "Google Analytics 4",
    roles: ["traffic"],
    trust: "verified",
    summary: "Active users and sessions via the GA4 Data API with a Viewer service account.",
    detects: ["@next/third-parties/google", "gtag", "NEXT_PUBLIC_GA_ID", "GA_MEASUREMENT_ID"],
    credentials: [
      { key: "propertyId", label: "Property ID", secret: false, whereToFind: "GA4 → Admin → Property settings (numeric)", envVarHints: ["GA4_PROPERTY_ID"] },
      { key: "serviceAccount", label: "Service account JSON", secret: true, whereToFind: "Google Cloud → Service Accounts → create → Keys → JSON; add its email as Viewer in GA4 property access; enable the Analytics Data API", envVarHints: ["GA4_SERVICE_ACCOUNT"] },
    ],
    permissions: ["Property access: Viewer only."],
    reads: "runReport with activeUsers + sessions. Aggregates only.",
    neverSent: NEVER,
  },
  {
    provider: "stripe",
    label: "Stripe",
    roles: ["conversion"],
    trust: "verified",
    summary: "Converted users (paid subscription state) and trial users from a restricted read-only key. Conversion state only — UserTrack never reads or stores amounts. A Stripe customer that never paid is not a converted user.",
    detects: ["stripe", "@stripe/stripe-js", "STRIPE_SECRET_KEY"],
    credentials: [
      { key: "secretKey", label: "Restricted key", secret: true, whereToFind: "Stripe → Developers → API keys → Create restricted key: Subscriptions = Read, everything else None", envVarHints: ["STRIPE_RESTRICTED_KEY"], format: "rk_live_…" },
      MODE_CREDENTIAL,
    ],
    permissions: ["Never use the full secret key (sk_live_). Create a restricted key with Subscriptions: Read only.", "UserTrack never modifies subscriptions or customers."],
    reads: "GET /v1/subscriptions by status (paginated): status, customer id, trial/start dates, metadata.userId. Prices, invoices and amounts are never requested.",
    neverSent: NEVER_PAYMENTS,
  },
  {
    provider: "revenuecat",
    label: "RevenueCat",
    roles: ["conversion"],
    trust: "verified",
    summary: "Trial and converted users for iOS / Android subscription apps from the v2 overview metrics (active trials, active subscriptions). RevenueCat customers — including anonymous app user ids — are never counted as registered users.",
    detects: ["revenuecat", "react-native-purchases", "purchases_flutter", "RevenueCat", "Purchases", "REVENUECAT_API_KEY"],
    credentials: [
      { key: "apiKey", label: "Secret API key (v2)", secret: true, whereToFind: "RevenueCat → Project settings → API keys → New secret key (v2) with only Charts & Metrics → Read", envVarHints: ["REVENUECAT_SECRET_KEY", "REVENUECAT_API_KEY"], format: "sk_…" },
      { key: "projectId", label: "Project ID", secret: false, whereToFind: "RevenueCat → Project settings → General", envVarHints: ["REVENUECAT_PROJECT_ID"], format: "proj1ab2c3d4" },
      { key: "mode", label: "Converted means", secret: false, optional: true, whereToFind: "RevenueCat supports active_paid only (active subscriptions). Use a JSON endpoint for other definitions.", envVarHints: [], format: "active_paid" },
    ],
    permissions: ["Create a dedicated v2 secret key with only Charts & Metrics → Read. Never the public SDK key, never a key with customer or purchase permissions."],
    reads: "GET /v2/projects/{id}/metrics/overview → active_trials and active_subscriptions only. MRR / revenue values in the same response are discarded.",
    neverSent: NEVER_PAYMENTS,
  },
  {
    provider: "paddle",
    label: "Paddle",
    roles: ["conversion"],
    trust: "verified",
    summary: "Converted (billed at least once) and trial users from Paddle Billing subscriptions with a read-only API key.",
    detects: ["paddle", "@paddle/paddle-js", "@paddle/paddle-node-sdk", "PADDLE_API_KEY"],
    credentials: [
      { key: "apiKey", label: "API key", secret: true, whereToFind: "Paddle → Developer tools → Authentication → New API key with Subscriptions → Read only", envVarHints: ["PADDLE_API_KEY"], format: "pdl_live_apikey_…" },
      { key: "environment", label: "Environment", secret: false, optional: true, whereToFind: "live (default) or sandbox", envVarHints: ["PADDLE_ENVIRONMENT"], format: "live | sandbox" },
      MODE_CREDENTIAL,
    ],
    permissions: ["API key with Subscriptions: Read only. No transactions, prices or customer write permissions."],
    reads: "GET /subscriptions by status: status, customer id, first_billed_at, custom_data.userId. No transactions or prices.",
    neverSent: NEVER_PAYMENTS,
  },
  {
    provider: "lemonsqueezy",
    label: "Lemon Squeezy",
    roles: ["conversion"],
    trust: "verified",
    summary: "Converted and trial users from Lemon Squeezy subscriptions (and paid orders for ever-paid modes).",
    detects: ["lemonsqueezy", "@lemonsqueezy/lemonsqueezy.js", "LEMONSQUEEZY_API_KEY"],
    credentials: [
      { key: "apiKey", label: "API key", secret: true, whereToFind: "Lemon Squeezy → Settings → API → Create API key", envVarHints: ["LEMONSQUEEZY_API_KEY", "LEMON_SQUEEZY_API_KEY"], format: "eyJ0eXAiOiJKV1Qi…" },
      { key: "storeId", label: "Store ID", secret: false, optional: true, whereToFind: "Settings → Stores; empty = all stores of the account", envVarHints: ["LEMONSQUEEZY_STORE_ID"], format: "12345" },
      MODE_CREDENTIAL,
    ],
    permissions: ["Lemon Squeezy API keys are account-wide; UserTrack only calls the subscriptions and orders list endpoints and never writes."],
    reads: "GET /v1/subscriptions (status, customer id, trial dates) and, for ever-paid modes, GET /v1/orders (status, customer id). Prices and emails in the response are dropped at parse time.",
    neverSent: NEVER_PAYMENTS,
  },
  {
    provider: "chargebee",
    label: "Chargebee",
    roles: ["conversion"],
    trust: "verified",
    summary: "Converted (activated subscription) and trial users from Chargebee subscriptions with a read-only API key.",
    detects: ["chargebee", "@chargebee/chargebee-js", "CHARGEBEE_API_KEY"],
    credentials: [
      { key: "site", label: "Site", secret: false, whereToFind: "The part before .chargebee.com", envVarHints: ["CHARGEBEE_SITE"], format: "acme" },
      { key: "apiKey", label: "Read-only API key", secret: true, whereToFind: "Chargebee → Settings → Configure Chargebee → API keys → Add API key → type Read-only", envVarHints: ["CHARGEBEE_API_KEY"], format: "live_…" },
      MODE_CREDENTIAL,
    ],
    permissions: ["Create a Read-only API key. Never a full-access key."],
    reads: "GET /api/v2/subscriptions by status: status, customer id, trial and activation timestamps, meta_data.userId. No invoices or amounts.",
    neverSent: NEVER_PAYMENTS,
  },
  {
    provider: "postgres",
    label: "PostgreSQL (read-only)",
    roles: ["users", "activation"],
    trust: "verified",
    summary: "Any SaaS with a Postgres database: a read-only connection string + the users table. Aggregate SQL only (count(*), count per day); rows are never read.",
    detects: ["pg", "postgres", "postgresql", "DATABASE_URL", "@neondatabase/serverless", "@vercel/postgres", "pg-promise", "prisma:postgresql", "drizzle-pg"],
    credentials: [
      { key: "connectionString", label: "Read-only connection string", secret: true, whereToFind: "Your database provider's connection panel (Neon, Railway, RDS, Render, Fly, Supabase…). Create a dedicated read-only role first (see permissions); enable SSL. UserTrack's IPs are not fixed, so the host must accept internet connections (or use the provider's pooler).", envVarHints: ["DATABASE_URL", "POSTGRES_URL", "PG_CONNECTION_STRING"], format: "postgresql://usertrack_ro:<password>@host:5432/dbname?sslmode=require" },
      { key: "tableRef", label: "Users table", secret: false, roles: ["users"], whereToFind: "The table (or view) with exactly one row per user, e.g. public.users. Look at the ORM schema / migrations.", envVarHints: [], format: "schema.table" },
      { key: "tableRef", label: "Activation table", secret: false, roles: ["activation"], optional: true, whereToFind: "A table with one row per activated user (e.g. workspaces with an owner_id). Alternatively pass `sql`.", envVarHints: [], format: "schema.table" },
      { key: "createdAtColumn", label: "Signup timestamp column", secret: false, optional: true, whereToFind: "created_at / createdAt / inserted_at on that table (timestamp or epoch). Unlocks 24h/7d/30d signups and 30-day history.", envVarHints: [] },
      { key: "deletedAtColumn", label: "Soft-delete column", secret: false, optional: true, whereToFind: "deleted_at if the table soft-deletes users; rows with a value are excluded.", envVarHints: [] },
      { key: "sql", label: "Custom activation SQL", secret: false, optional: true, roles: ["activation"], whereToFind: "One SELECT returning a single count; $1 is the 'since' timestamp, e.g. SELECT count(distinct user_id) FROM projects WHERE created_at >= $1", envVarHints: [] },
    ],
    permissions: ["Create a read-only role: CREATE ROLE usertrack_ro LOGIN PASSWORD '…'; GRANT CONNECT ON DATABASE <db> TO usertrack_ro; GRANT USAGE ON SCHEMA public TO usertrack_ro; GRANT SELECT ON public.users TO usertrack_ro;", "Never hand over the application's main DATABASE_URL if it has write access."],
    reads: "SELECT count(*) with optional created_at >= $1 / deleted_at IS NULL filters, and one GROUP BY day query for history. The session is forced read-only; statements time out after 20s.",
    neverSent: NEVER,
  },
  {
    provider: "endpoint",
    label: "JSON endpoint on your own domain",
    roles: ["users", "activation", "traffic", "conversion"],
    trust: "conditional",
    summary: "A tiny authenticated route in your own app that returns aggregate counts. Verified when it lives on the product's domain. Prefer the native SDK (provider native) when you can add a package; the endpoint is the universal fallback for any stack (raw SQL, Mongo, analytics exports).",
    detects: ["pg", "mysql2", "amplitude", "@amplitude/analytics-browser", "mixpanel", "mixpanel-browser"],
    credentials: [
      { key: "url", label: "Endpoint URL", secret: false, whereToFind: "The route you add, on the same domain as the product (e.g. https://app.example.com/api/usertrack)", envVarHints: [], format: "https://…" },
      { key: "token", label: "Bearer token", secret: true, optional: true, whereToFind: "Generate a random secret (openssl rand -hex 32), set it as USERTRACK_ENDPOINT_TOKEN in the app, and give the same value to UserTrack", envVarHints: ["USERTRACK_ENDPOINT_TOKEN"] },
    ],
    permissions: ["The route runs inside your app with your own DB access; expose a count only."],
    reads: "One GET per sync. users: { totalUsers, newUsers24h/7d/30d?, activeUsers30d? }; activation: { activatedUsers, activated24h/7d/30d? }; traffic: { visitors30d, sessions30d? }; conversion: { convertedUsers, newConverted24h/7d/30d?, trialUsers?, newTrials7d/30d?, mode? }. Optional identities: { signedUp | activated | trial | converted: [{ id, at? }] } with stable user ids (never emails) for cohort matching.",
    neverSent: NEVER,
  },
  {
    provider: "manual",
    label: "Manual (self-reported)",
    roles: ["users"],
    trust: "unverified",
    summary: "Type a number. Always labelled self-reported, never ranked. Last resort only.",
    detects: [],
    credentials: [{ key: "totalUsers", label: "Total users", secret: false, whereToFind: "Ask the founder", envVarHints: [], format: "integer" }],
    permissions: [],
    reads: "Nothing.",
    neverSent: NEVER,
  },
];

export const catalogEntry = (provider: string) => INTEGRATION_CATALOG.find((c) => c.provider === provider) ?? null;

// Aliases an agent might report after scanning package.json / env files → UserTrack provider.
const DETECTION_ALIASES: Record<string, ProviderKind> = {
  clerk: "clerk",
  supabase: "supabase",
  firebase: "firebase",
  "firebase-auth": "firebase",
  auth0: "auth0",
  posthog: "posthog",
  plausible: "plausible",
  ga4: "ga4",
  "google-analytics": "ga4",
  gtag: "ga4",
  stripe: "stripe",
  endpoint: "endpoint",
  manual: "manual",
  native: "native",
  "better-auth": "native",
  betterauth: "native",
  "better_auth": "native",
  "convex-dev-better-auth": "native",
  nextauth: "native",
  "next-auth": "native",
  "auth.js": "native",
  authjs: "native",
  auth: "native",
  lucia: "native",
  convex: "native",
  prisma: "native",
  drizzle: "native",
  mongoose: "native",
  mongodb: "native",
  postgres: "postgres",
  postgresql: "postgres",
  pg: "postgres",
  "pg-promise": "postgres",
  "postgres.js": "postgres",
  neon: "postgres",
  neondatabase: "postgres",
  "vercel-postgres": "postgres",
  "database-url": "postgres",
  "prisma:postgresql": "native",
  "drizzle-pg": "native",
  "supabase-db": "supabase",
  mysql: "native",
  sqlite: "native",
  kysely: "native",
  sequelize: "native",
  typeorm: "native",
  "custom-db": "native",
  custom: "native",
  "custom-auth": "native",
  // Mobile SDKs
  "react-native-firebase": "firebase",
  firebaseauth: "firebase",
  "posthog-react-native": "posthog",
  "posthog-ios": "posthog",
  "posthog-android": "posthog",
  "posthog-flutter": "posthog",
  // Payments (conversion state only)
  revenuecat: "revenuecat",
  "react-native-purchases": "revenuecat",
  "purchases-flutter": "revenuecat",
  purchases: "revenuecat",
  paddle: "paddle",
  lemonsqueezy: "lemonsqueezy",
  "lemon-squeezy": "lemonsqueezy",
  chargebee: "chargebee",
  // Product analytics without a native reader: activation via the endpoint provider.
  amplitude: "endpoint",
  mixpanel: "endpoint",
  "mixpanel-browser": "endpoint",
};

// Signals that are authentication *methods* (or store SDKs), never a user store: they classify the project, not a provider.
const AUTH_METHOD_SIGNALS: [RegExp, string][] = [
  [/apple|authenticationservices/i, "apple"],
  [/google[-_]?sign[-_]?in|googlesignin|google-auth-library|google_sign_in/i, "google"],
  [/github/i, "github"],
  [/microsoft|azure-ad|entra/i, "microsoft"],
  [/phone|sms|otp/i, "phone"],
  [/email|password|magic[-_]?link/i, "email"],
];
const NOT_A_PROVIDER = /storekit|authenticationservices|sign-?in-?with-?apple|apple-authentication|google[-_]?sign[-_]?in|googlesignin|google_sign_in/i;

export function detectAuthMethods(detected: readonly string[] = []) {
  const out = new Set<string>();
  for (const raw of detected) for (const [re, method] of AUTH_METHOD_SIGNALS) if (re.test(raw)) out.add(method);
  return [...out];
}

export const detectProjectType = (detected: readonly string[] = []): ProjectType => (detected.some((d) => /react-native|expo|flutter|swift|kotlin|storekit|-ios$|-android$|purchases|firebase_auth/i.test(d)) ? "mobile" : "web");

export function normalizeDetected(detected: readonly string[] = []) {
  const out: { raw: string; provider: ProviderKind }[] = [];
  for (const raw of detected) {
    if (NOT_A_PROVIDER.test(raw)) continue;
    const key = raw.trim().toLowerCase().replace(/^@/, "").replace(/\/.*$/, "").replace(/_/g, "-");
    const hit = DETECTION_ALIASES[key] ?? INTEGRATION_CATALOG.find((c) => c.detects.some((d) => d.toLowerCase() === raw.trim().toLowerCase() || d.toLowerCase().replace(/^@/, "").split("/")[0] === key))?.provider;
    if (hit) out.push({ raw, provider: hit });
  }
  return out;
}

// Which SDK adapter a native signal maps to; first match wins (Better Auth with a Prisma adapter is still Better Auth).
const NATIVE_SOURCE_SIGNALS: [RegExp, NativeSource][] = [
  [/better[-_]?auth/i, "better-auth"],
  [/next[-_]?auth|auth\.js|^authjs$|^@auth\/|^auth$|^AUTH_SECRET$|^NEXTAUTH_/i, "authjs"],
  [/^convex/i, "convex"],
  [/prisma/i, "prisma"],
  [/drizzle/i, "drizzle"],
];
export function detectNativeSource(detected: readonly string[] = []): NativeSource | undefined {
  const raw = detected.map((d) => d.trim());
  for (const [re, source] of NATIVE_SOURCE_SIGNALS) if (raw.some((d) => re.test(d))) return source;
  return normalizeDetected(raw).some((d) => d.provider === "native") ? "custom" : undefined;
}
// Better Auth / Auth.js / Convex own the user store: the SDK is the natural source. ORM-only signals (Prisma, Drizzle, custom)
// rank after hosted auth providers, which need no code change, but before a raw database connection.
const STRONG_NATIVE: NativeSource[] = ["better-auth", "authjs", "convex"];
// Direct auth providers first (least setup), then a read-only database, then the universal endpoint.
const USERS_PRIORITY: ProviderKind[] = ["native", "supabase", "clerk", "firebase", "auth0", "postgres", "endpoint", "manual"];
const usersPriority = (source: NativeSource | undefined): ProviderKind[] => (!source || STRONG_NATIVE.includes(source) ? USERS_PRIORITY : ["supabase", "clerk", "firebase", "auth0", "native", "postgres", "endpoint", "manual"]);

// Conversion sources by preference: mobile subscriptions first, then web billing, then the universal endpoint.
export const CONVERSION_PRIORITY: ProviderKind[] = ["revenuecat", "stripe", "paddle", "lemonsqueezy", "chargebee", "native", "endpoint"];
const CONVERSION_REASON: Partial<Record<ProviderKind, string>> = {
  revenuecat: "RevenueCat detected — Trial and Converted users from active trials / active subscriptions with a Charts & Metrics read-only key. RevenueCat customers are never counted as registered users; conversion state only, no revenue; private by default.",
  stripe: "Stripe detected — converted users from paid subscription state via a restricted read-only key. Conversion state only, no revenue; private by default.",
  paddle: "Paddle detected — converted users from billed subscriptions via a read-only API key. Conversion state only, no revenue; private by default.",
  lemonsqueezy: "Lemon Squeezy detected — converted users from subscriptions and paid orders via the API key. Conversion state only, no revenue; private by default.",
  chargebee: "Chargebee detected — converted users from activated subscriptions via a read-only API key. Conversion state only, no revenue; private by default.",
  native: "No payment provider detected — the UserTrack SDK handler can report converted / trial users from your own tables (conversion: { converted, trial? } — counts only, never amounts); private by default.",
};

export interface RecommendInput {
  detectedProviders?: readonly string[];
  framework?: string;
  projectType?: ProjectType;
  detectedAuth?: readonly string[];
  detectedAnalytics?: readonly string[];
  detectedPayments?: readonly string[];
}

// Best users-role source first, then optional extras (activation, traffic, conversion) composed into one lifecycle plan.
export function recommendIntegrations(input: RecommendInput) {
  const raw = [...(input.detectedProviders ?? []), ...(input.detectedAuth ?? []), ...(input.detectedAnalytics ?? []), ...(input.detectedPayments ?? [])];
  const detected = normalizeDetected(raw);
  const kinds = new Set(detected.map((d) => d.provider));
  const authMethods = detectAuthMethods(raw);
  const projectType = input.projectType ?? detectProjectType(raw);
  const reasoning: string[] = [];
  const nativeSource = detectNativeSource(raw);
  let users: ProviderKind = "endpoint";
  for (const k of usersPriority(nativeSource)) {
    if (kinds.has(k) && k !== "manual") {
      users = k;
      const hits = detected.filter((d) => d.provider === k).map((d) => d.raw).join(", ");
      reasoning.push(k === "native" ? (nativeSource === "better-auth" ? `Better Auth detected (${hits}) — an official plugin exists: install @usertrack/better-auth, add userTrack() to the plugins array and UserTrack pulls signed aggregate metrics (no PII, no database credentials). Use usertrack_get_native_setup { source: "better-auth" }.` : `${NATIVE_SOURCE_LABEL[nativeSource ?? "custom"]} detected (${hits}) — install @usertrack/node, mount one signed handler with a count source (${nativeSource ?? "custom"} adapter) and UserTrack pulls verified aggregate metrics; activation and conversion can come from the same handler. Use usertrack_get_native_setup { source: "${nativeSource ?? "custom"}" }.`) : `${catalogEntry(k)!.label} detected (${hits}) — it can report user counts directly with a read-only credential.`);
      break;
    }
  }
  if (users === "postgres") reasoning.push("A read-only PostgreSQL connection counts users straight from the users table with aggregate SQL — no code change in the product, verified.");
  if (users === "endpoint" && authMethods.some((m) => m === "apple" || m === "google")) reasoning.push("Sign in with Apple / Google are authentication methods, not a user store, so they never become the users source. Registered users must come from where accounts are persisted (Firebase Auth, Supabase, Auth0, a database) — none was detected, so add a small JSON endpoint on your backend that returns aggregate counts.");
  else if (users === "endpoint") reasoning.push(kinds.size ? "No supported auth provider or Postgres database was detected, so the safest verified path is a small JSON endpoint on the product's own domain that returns aggregate counts from your existing database." : "Nothing was detected; a JSON endpoint on the product's own domain is the universal verified option. Use manual only if no data source can be exposed.");
  if (raw.some((d) => /storekit/i.test(d)) && !kinds.has("revenuecat")) reasoning.push("StoreKit detected — App Store purchases cannot be read by UserTrack directly; RevenueCat (or a JSON endpoint on your backend) provides the Trial and Converted stages.");
  const extras: { role: Role; provider: ProviderKind; reason: string }[] = [];
  if (kinds.has("posthog")) extras.push({ role: "activation", provider: "posthog", reason: "PostHog detected — pick the event that means a user really started and UserTrack will show activated users + activation rate." });
  else if (users === "native") extras.push({ role: "activation", provider: "native", reason: "The same UserTrack SDK handler can report activated users: pass activation: <count source> (a table with one row per activated user, e.g. workspaces / projects) — attached automatically on the next sync." });
  else if (users === "supabase") extras.push({ role: "activation", provider: "supabase", reason: "A Supabase table with one row per activated user (or a custom SQL count with the database connection string) unlocks activation metrics." });
  else if (users === "postgres" || kinds.has("postgres")) extras.push({ role: "activation", provider: "postgres", reason: "The same read-only connection can count activated users: a table with one row per activated user, or one SELECT count(distinct user_id) … WHERE created_at >= $1." });
  else if (raw.some((d) => /amplitude|mixpanel/i.test(d))) extras.push({ role: "activation", provider: "endpoint", reason: "Amplitude / Mixpanel detected — UserTrack has no native reader for them; expose { activatedUsers } from your backend (query their export API or your own events table) on the JSON endpoint." });
  if (kinds.has("plausible")) extras.push({ role: "traffic", provider: "plausible", reason: "Plausible detected — visitors and sessions for the funnel (private by default)." });
  else if (kinds.has("ga4")) extras.push({ role: "traffic", provider: "ga4", reason: "Google Analytics detected — active users and sessions for the funnel (private by default)." });
  const conversion = CONVERSION_PRIORITY.find((k) => k !== "endpoint" && (k === "native" ? users === "native" : kinds.has(k)));
  if (conversion) extras.push({ role: "conversion", provider: conversion, reason: CONVERSION_REASON[conversion]! });
  const pick = (role: Role) => { const e = extras.find((x) => x.role === role); return e ? { provider: e.provider, reason: e.reason } : undefined; };
  const composition = { users: { provider: users, reason: reasoning[0], ...(users === "native" ? { source: nativeSource ?? "custom" } : {}) }, activation: pick("activation"), traffic: pick("traffic"), conversion: pick("conversion") };
  const lifecycle: LifecycleStage[] = [...(composition.traffic ? ["reached" as const] : []), "signed_up", ...(composition.activation ? ["activated" as const] : []), ...(composition.conversion ? ["trial" as const, "converted" as const] : [])];
  return {
    recommended: { role: "users" as Role, provider: users, entry: catalogEntry(users)! },
    alternatives: usersPriority(nativeSource).filter((k) => k !== users).map((k) => ({ provider: k, label: catalogEntry(k)!.label, trust: catalogEntry(k)!.trust })),
    nativeSource: users === "native" ? (nativeSource ?? "custom") : undefined,
    optionalExtras: extras,
    detected,
    reasoning,
    composition,
    authMethods,
    projectType,
    lifecycle,
  };
}

const MODE_MEANING: Record<ConversionMode, string> = {
  active_paid: "A unique user who currently has a paid subscription (trials, cancelled and expired subscriptions excluded). Best for subscription products.",
  ever_paid: "A unique user who paid at least once, even if they cancelled since. Best for lifetime conversion.",
  first_payment: "Same set as ever_paid, counted at the first successful payment — the cohort-friendly definition.",
};
const CONVERSION_IDENTITY: Record<string, { recommendation: string; howTo: string }> = {
  stripe: { recommendation: "Set metadata.userId on every subscription (your auth user id).", howTo: "stripe.subscriptions.create({ …, metadata: { userId } }) — or set it on the Checkout Session's subscription_data.metadata. UserTrack reads metadata.userId and falls back to the customer id." },
  revenuecat: { recommendation: "Use your auth user id as the RevenueCat app_user_id.", howTo: "Purchases.configure({ apiKey, appUserID: uid }) after login (or Purchases.logIn(uid)). Note: RevenueCat overview metrics do not expose identities yet, so cohorts stay aggregate until a JSON endpoint reports converted ids." },
  paddle: { recommendation: "Set custom_data.userId on subscriptions / checkouts.", howTo: "Paddle.Checkout.open({ customData: { userId } }) — UserTrack reads subscription.custom_data.userId and falls back to customer_id." },
  chargebee: { recommendation: "Set meta_data.userId on subscriptions.", howTo: "Pass meta_data: { userId } when creating the subscription — UserTrack reads it and falls back to customer_id." },
  lemonsqueezy: { recommendation: "Lemon Squeezy exposes only customer_id; store it next to your user.", howTo: "Save the customer_id from the order webhook on your user row; report converted ids from a JSON endpoint if you need cohort matching." },
  endpoint: { recommendation: "Return identities.converted / identities.trial with your own user ids.", howTo: "{ convertedUsers, trialUsers, identities: { converted: [{ id, at }], trial: [{ id, at }] } } — stable ids only, never emails." },
  native: { recommendation: "Return identities from the SDK handler with your own user ids.", howTo: "createUserTrackHandler({ …, identities: async () => ({ converted: [{ id, at }], trial: [{ id, at }] }) }) — stable ids only, never emails." },
};
const CONVERSION_PRIVACY = ["No amounts, prices, invoices or MRR are ever read or stored.", "No PII: only counts and salted-hashed stable ids.", "Read-only credential with the minimum permission listed; UserTrack never modifies subscriptions or customers.", "Private by default — connection ≠ publication; the founder switches conversion metrics on per metric."];
const REVENUECAT_NOTES = ["RevenueCat customers include anonymous app user ids ($RCAnonymousID:…) and every install — they are never counted as registered users; Signed up comes from your identity source (Firebase Auth, Supabase, a database…).", "Only active_paid is supported (active subscriptions); use a JSON endpoint for ever_paid / first_payment."];

// Conversion source plan: which payment provider, what "converted" means, least-privilege credential, identity matching.
export function conversionSetup(input: { provider?: string; detectedProviders?: readonly string[]; projectType?: ProjectType; projectId?: string }) {
  const kinds = new Set(normalizeDetected(input.detectedProviders).map((d) => d.provider));
  const provider = (input.provider as ProviderKind | undefined) ?? CONVERSION_PRIORITY.find((k) => k !== "native" && kinds.has(k)) ?? (input.projectType === "mobile" ? "revenuecat" : "endpoint");
  const entry = catalogEntry(provider);
  if (!entry || !entry.roles.includes("conversion")) return null;
  const modes: ConversionMode[] = provider === "revenuecat" ? ["active_paid"] : ["active_paid", "ever_paid", "first_payment"];
  const requiredCredentials = provider === "native" ? [] : entry.credentials.filter((c) => !c.roles || c.roles.includes("conversion"));
  const projectRef = input.projectId ?? "<projectId>";
  const steps: SetupStep[] = provider === "native" ? [
    { id: "native:conversion", title: "Report conversion from the UserTrack SDK handler", detail: "Add conversion: { converted: <count source of users with an active paid subscription>, trial?: <count source of users on a trial>, mode?: \"active_paid\" } to createUserTrackHandler({ … }) (e.g. prismaUsers(prisma.subscription, { where: { status: \"active\" } })). Counts only — never amounts. Deploy.", action: "modify_repo" },
    { id: "verify", title: "Verify", detail: `Call usertrack_verify_integration with { projectId: "${projectRef}", role: "users" } — UserTrack attaches the conversion role automatically when the handler reports it; then usertrack_verify_integration with role "conversion".`, action: "verify", tool: "usertrack_verify_integration" },
  ] : [
    ...requiredCredentials.filter((c) => c.key !== "mode").map<SetupStep>((c) => ({ id: `collect:${c.key}`, title: `${c.optional ? "Optionally locate" : "Locate"} ${c.label}`, detail: `${c.whereToFind}${c.envVarHints.length ? ` Check the repo's env files for ${c.envVarHints.join(" / ")} first.` : ""}${c.secret ? " Keep it server-side; never commit it." : ""}`, action: c.secret ? "collect_credential" : "ask_user" })),
    { id: "configure", title: "Submit the conversion source", detail: `Call usertrack_configure_integration with { projectId: "${projectRef}", provider: "${provider}", role: "conversion", config: { ${requiredCredentials.map((r) => `${r.key}: …`).join(", ")} } }.`, action: "call_tool", tool: "usertrack_configure_integration" },
    { id: "verify", title: "Verify", detail: `Call usertrack_verify_integration with { projectId: "${projectRef}", role: "conversion" }. detected.count = converted users; the count must be ≤ total users.`, action: "verify", tool: "usertrack_verify_integration" },
  ];
  return {
    provider,
    label: entry.label,
    recommendedDefinition: { mode: "active_paid" as const, meaning: MODE_MEANING.active_paid },
    alternatives: modes.filter((m) => m !== "active_paid").map((mode) => ({ mode, meaning: MODE_MEANING[mode] })),
    requiredCredentials: requiredCredentials.map((c) => ({ ...c, roles: undefined })),
    minimumPermissions: entry.permissions,
    readOnly: true as const,
    identityMatching: CONVERSION_IDENTITY[provider] ?? CONVERSION_IDENTITY.endpoint,
    privacyRules: CONVERSION_PRIVACY,
    trialSupported: true,
    configShape: Object.fromEntries(requiredCredentials.map((r) => [r.key, `${r.secret ? "secret " : ""}string${r.optional ? " (optional)" : ""}`])),
    steps,
    notes: provider === "revenuecat" ? REVENUECAT_NOTES : provider === "stripe" ? ["A Stripe customer that never paid is never a converted user; one-time payments are not covered."] : [],
    nextTool: provider === "native" ? "usertrack_get_native_setup" : "usertrack_configure_integration",
  };
}

const IDENTITY_FIELD: Record<string, string> = { native: "your app's user id (identities.signedUp[].id from the SDK handler; Better Auth: user.id)", better_auth: "better-auth user.id (session.user.id)", firebase: "firebase.uid", supabase: "supabase.auth.users.id", clerk: "clerk.userId", auth0: "auth0.user_id", postgres: "users.<idColumn>", endpoint: "identities.signedUp[].id (your user id)" };
const ANALYTICS_MAPPING: Record<string, { to: string; how: string }> = {
  posthog: { to: "posthog.distinct_id", how: "Call posthog.identify(uid) right after login (web: posthog-js; mobile: PostHog SDK identify(uid)). UserTrack reads identified distinct_ids of the activation event; anonymous device ids are skipped." },
  supabase: { to: "supabase.<activation table>.<idColumn>", how: "The activation table must carry the auth user id (e.g. owner_id); pass idColumn in the configuration." },
  postgres: { to: "postgres.<activation table>.<idColumn>", how: "The activation table must carry the user id; pass idColumn in the configuration." },
  endpoint: { to: "identities.activated[].id", how: "Report the same user ids you use for signedUp under identities.activated." },
  native: { to: "identities.activated[].id", how: "Return identities.activated with the same user ids from the SDK handler's identities() function." },
};
const CONVERSION_MAPPING: Record<string, { to: string; how: string }> = {
  revenuecat: { to: "revenuecat.app_user_id", how: CONVERSION_IDENTITY.revenuecat.howTo },
  stripe: { to: "stripe.subscription.metadata.userId", how: CONVERSION_IDENTITY.stripe.howTo },
  paddle: { to: "paddle.subscription.custom_data.userId", how: CONVERSION_IDENTITY.paddle.howTo },
  chargebee: { to: "chargebee.subscription.meta_data.userId", how: CONVERSION_IDENTITY.chargebee.howTo },
  lemonsqueezy: { to: "lemonsqueezy.customer_id", how: CONVERSION_IDENTITY.lemonsqueezy.howTo },
  endpoint: { to: "identities.converted[].id", how: CONVERSION_IDENTITY.endpoint.howTo },
  native: { to: "identities.converted[].id", how: CONVERSION_IDENTITY.native.howTo },
};

// How to carry one stable user id across the identity, analytics and conversion sources so cohorts can be traced. No PII ever.
export function identityMappingGuidance(input: { identitySource: string; analyticsSource?: string; conversionSource?: string; projectType?: ProjectType }) {
  const from = IDENTITY_FIELD[input.identitySource] ?? `${input.identitySource}.userId`;
  const recommendedMapping: { from: string; to: string; how: string }[] = [];
  const a = input.analyticsSource ? ANALYTICS_MAPPING[input.analyticsSource] : undefined;
  if (a) recommendedMapping.push({ from, ...a });
  const c = input.conversionSource ? CONVERSION_MAPPING[input.conversionSource] : undefined;
  if (c) recommendedMapping.push({ from, ...c });
  return {
    identitySource: input.identitySource,
    analyticsSource: input.analyticsSource ?? null,
    conversionSource: input.conversionSource ?? null,
    projectType: input.projectType ?? "web",
    recommendedMapping,
    privacy: ["Never send emails, names, phone numbers or device fingerprints — only the opaque user id your auth system already issues.", "Ids are salted and SHA-256 hashed per project before storage; the raw id is discarded.", "UserTrack never shows a single user: only aggregate cohort counts and medians.", input.identitySource === "firebase" && input.projectType === "mobile" ? "Sign in with Apple relay emails are PII too — use the Firebase uid, never the Apple identifier or email." : "Anonymous ids (device ids, $RCAnonymousID) are skipped and never matched."],
    howUserTrackMatches: "ids are salted + SHA-256 hashed per project before storage; only aggregate cohort counts are ever shown",
    qualityLevels: IDENTITY_QUALITY_META,
    rules: COHORT_RULES,
  };
}

// Activation event ranking: outcome events win, traffic / auth / technical events are rejected with a reason.
const REJECTED_EVENTS: [RegExp, string][] = [
  [/^\$?(pageview|page_view|screen_view|\$screen)$/i, "fires on every visit — a traffic signal, not a value moment"],
  [/^(app_open|app_opened|session_start|app_install|app_installed|\$identify|identify)$/i, "fires for every install / session / identify call — everyone who signs up triggers it"],
  [/^(login|log_in|sign_in|signin|logged_in)$/i, "login is not activation: returning users fire it without doing anything"],
  [/^(signup|sign_up|signed_up|user_created|account_created|registered|register)$/i, "this is the Signed up stage — activation must happen after the account exists"],
  [/^(click|button_click|clicked|\$autocapture|tap)$/i, "generic interaction with no product outcome"],
];
const OUTCOME_SCORE: [RegExp, number][] = [
  [/^first_/i, 4],
  [/(onboarding_completed|project_created|workspace_created|invite_(sent|accepted))/i, 3],
  [/(_created|_completed|_published|_sent|_deployed|_generated|_uploaded)$/i, 2],
  [/complete|created|first|onboard|setup|run|sent|publish|deploy|invite|upload|generate|export/i, 1],
];
export function rankActivationEvents(candidateEvents: readonly string[] = [], source?: string) {
  const rejected: { event: string; reason: string }[] = [];
  const scored: { event: string; score: number }[] = [];
  for (const event of candidateEvents) {
    const bad = REJECTED_EVENTS.find(([re]) => re.test(event.trim()));
    if (bad) rejected.push({ event, reason: bad[1] });
    else scored.push({ event, score: OUTCOME_SCORE.find(([re]) => re.test(event))?.[1] ?? 0 });
  }
  scored.sort((a, b) => b.score - a.score);
  const best = scored[0]?.score ? scored[0] : undefined;
  return {
    recommendedEvent: best?.event,
    reason: best ? `${best.event} looks like a product outcome (${best.score >= 3 ? "first-value / completion event" : best.score === 2 ? "creation / completion event" : "contains an outcome keyword"}) — it should fire once per user when they reach the core value.` : candidateEvents.length ? "No candidate looks like an outcome event; add one that fires when a user reaches the core value (e.g. project_created, onboarding_completed) or pick a table / SQL count instead." : "No candidate events were given; grep the repo for capture(...) / track(...) calls.",
    source: source ?? null,
    rejected,
    alternatives: scored.filter((s) => s !== best).map((s) => ({ event: s.event, looksLikeActivation: s.score > 0 })),
  };
}

export interface SetupStep {
  id: string;
  title: string;
  detail: string;
  action: "collect_credential" | "modify_repo" | "deploy" | "call_tool" | "ask_user" | "verify";
  tool?: string;
}

const SECURITY_RULES = [
  "Use the least privilege credential listed in requirements; never a full-access or admin key when a read-only one exists.",
  "Credentials go straight into usertrack_configure_integration; never print, log, or commit them, and never paste them into chat.",
  "UserTrack stores only aggregate counts and timestamps. Do not send emails, names, passwords, session tokens or per-user rows.",
  "Do not modify authentication, billing or database code beyond adding a read-only count endpoint when the endpoint provider is used.",
  "If a credential is missing, ask the founder for it — do not guess, and do not create new keys without telling them.",
];

function endpointTemplate(framework: string | undefined, orm: string | undefined) {
  const count = orm === "prisma" ? "await prisma.user.count()" : orm === "drizzle" ? "(await db.select({ n: count() }).from(users))[0].n" : orm === "mongoose" ? "await User.countDocuments()" : orm === "convex" ? "await fetchQuery(api.usertrack.totalUsers, {})" : orm === "better-auth" ? "/* count rows in your Better Auth `user` table */ await db.user.count()" : "/* replace with your own count query */ 0";
  const next = `// app/api/usertrack/route.ts — returns aggregate counts only. Verified by UserTrack because it lives on your domain.
export const dynamic = "force-dynamic";

export async function GET(req: Request) {
  const auth = req.headers.get("authorization") ?? "";
  if (auth !== \`Bearer \${process.env.USERTRACK_ENDPOINT_TOKEN}\`) return new Response("Unauthorized", { status: 401 });
  const totalUsers = ${count};
  return Response.json({ totalUsers });
}
`;
  const express = `// routes/usertrack.js — returns aggregate counts only.
app.get("/api/usertrack", async (req, res) => {
  if (req.headers.authorization !== \`Bearer \${process.env.USERTRACK_ENDPOINT_TOKEN}\`) return res.status(401).end();
  const totalUsers = ${count};
  res.json({ totalUsers });
});
`;
  if (framework === "express" || framework === "fastify" || framework === "hono" || framework === "node") return { framework: "express", path: "routes/usertrack.js", language: "javascript", code: express };
  return { framework: "nextjs", path: "app/api/usertrack/route.ts", language: "typescript", code: next };
}

// Deterministic instructions another coding agent can execute step by step.
export function integrationSetup(input: { provider: string; role?: Role; framework?: string; detectedProviders?: readonly string[]; websiteUrl?: string; projectId?: string }) {
  const entry = catalogEntry(input.provider);
  if (!entry) return null;
  const role: Role = input.role ?? (entry.roles.includes("users") ? "users" : entry.roles[0]);
  if (!entry.roles.includes(role)) return null;
  const rec = recommendIntegrations({ detectedProviders: input.detectedProviders, framework: input.framework });
  const endpointHints = normalizeDetected(input.detectedProviders).filter((d) => d.provider === "endpoint").map((d) => d.raw.toLowerCase().replace(/^@/, "").split("/")[0]);
  const detectedOrm = ["prisma", "drizzle", "mongoose", "convex"].find((o) => endpointHints.some((h) => h.startsWith(o))) ?? endpointHints[0];
  const requirements = entry.credentials.filter((c) => !c.roles || c.roles.includes(role));
  const projectRef = input.projectId ?? "<projectId>";
  const steps: SetupStep[] = [];
  for (const c of requirements) {
    steps.push({
      id: `collect:${c.key}`,
      title: `${c.optional ? "Optionally locate" : "Locate"} ${c.label}`,
      detail: `${c.whereToFind}${c.envVarHints.length ? ` Check the repo's env files for ${c.envVarHints.join(" / ")} first.` : ""}${c.secret ? " Keep it server-side; never commit it." : ""}`,
      action: c.secret ? "collect_credential" : "ask_user",
    });
  }
  const codeTemplates: { framework: string; path: string; language: string; code: string }[] = [];
  if (entry.provider === "endpoint") {
    const tpl = endpointTemplate(input.framework, detectedOrm);
    codeTemplates.push(tpl);
    steps.unshift(
      { id: "endpoint:token", title: "Create the endpoint token", detail: "Generate a random secret (e.g. openssl rand -hex 32) and add it to the app's environment as USERTRACK_ENDPOINT_TOKEN in every environment that serves the product domain.", action: "modify_repo" },
      { id: "endpoint:route", title: "Add the count route", detail: `Add ${tpl.path} using the code template. Return { "totalUsers": <integer> } from your users table; add newUsers24h/7d/30d and activeUsers30d if cheap. Never return user records.`, action: "modify_repo" },
      { id: "endpoint:deploy", title: "Deploy", detail: `The route must be reachable over HTTPS on the product domain${input.websiteUrl ? ` (${input.websiteUrl})` : ""} — endpoints on other hosts are accepted but labelled self-reported.`, action: "deploy" },
    );
  }
  if (entry.provider === "postgres" || (entry.provider === "supabase" && normalizeDetected(input.detectedProviders).some((d) => d.provider === "postgres"))) {
    codeTemplates.push({ framework: "sql", path: "usertrack-readonly-role.sql", language: "sql", code: `-- Run once as a superuser / owner. Replace <db>, <schema>, <table> and the password.\nCREATE ROLE usertrack_ro LOGIN PASSWORD '<generate with: openssl rand -hex 24>';\nGRANT CONNECT ON DATABASE <db> TO usertrack_ro;\nGRANT USAGE ON SCHEMA <schema> TO usertrack_ro;\nGRANT SELECT ON <schema>.<table> TO usertrack_ro;\n` });
    steps.unshift({ id: "postgres:role", title: "Create a read-only database role", detail: "Run the SQL template (or your provider's read-only role feature) so UserTrack never receives write access. Then build the connection string with that role; keep sslmode=require.", action: "modify_repo" });
  }
  let nativeSource: NativeSource | undefined;
  if (entry.provider === "native") {
    nativeSource = detectNativeSource(input.detectedProviders) ?? "custom";
    steps.splice(0, steps.length);
    const plan = nativeSetup({ source: nativeSource, projectId: input.projectId, packageManager: input.framework, framework: input.framework });
    for (const s of plan.steps) steps.push({ id: `native:${s.id}`, title: s.title, detail: s.detail, action: s.action, tool: s.tool });
    for (const f of plan.files) codeTemplates.push({ framework: "any", path: f.path, language: f.language, code: f.code });
  }
  if (entry.provider === "manual") {
    steps.push({ id: "manual:ask", title: "Confirm the number with the founder", detail: "Manual numbers are labelled self-reported and never ranked. Prefer any verified provider if one exists.", action: "ask_user" });
  }
  if (entry.provider !== "native") steps.push(
    { id: "configure", title: "Submit the configuration to UserTrack", detail: `Call usertrack_configure_integration with { projectId: "${projectRef}", provider: "${entry.provider}", role: "${role}", config: { ${requirements.map((r) => `${r.key}: …`).join(", ")} } }. UserTrack validates the shape, stores secrets encrypted and starts the first sync immediately.`, action: "call_tool", tool: "usertrack_configure_integration" },
    { id: "verify", title: "Verify the connection", detail: `Call usertrack_verify_integration with { projectId: "${projectRef}", role: "${role}" }. It performs a live read and returns the detected count, the verification level and an actionable error if anything is wrong. Wait ~5 seconds after configuring; retry at most 3 times.`, action: "verify", tool: "usertrack_verify_integration" },
    { id: "publish", title: "Publish and share", detail: `Once verified, call usertrack_update_project with { projectId: "${projectRef}", isPublic: true }, then usertrack_get_share_url and hand the public URL to the founder.`, action: "call_tool", tool: "usertrack_update_project" },
  );
  return {
    provider: entry.provider,
    label: entry.label,
    role,
    recommended: rec.recommended.provider === entry.provider && role === "users",
    trust: entry.trust,
    summary: entry.summary,
    requirements: requirements.map((c) => ({ ...c, roles: undefined })),
    permissions: entry.permissions,
    reads: entry.reads,
    neverSent: entry.neverSent,
    steps,
    securityRules: SECURITY_RULES,
    configShape: Object.fromEntries(requirements.map((r) => [r.key, `${r.secret ? "secret " : ""}${r.format === "integer" ? "integer" : "string"}${r.optional ? " (optional)" : ""}`])),
    codeTemplates,
    verification: { tool: "usertrack_verify_integration", args: { projectId: projectRef, role } },
    nextTool: entry.provider === "native" ? "usertrack_get_native_setup" : "usertrack_configure_integration",
    ...(nativeSource ? { source: nativeSource, package: NATIVE_PACKAGE[nativeSource] } : {}),
    optionalExtras: rec.optionalExtras,
  };
}
