// Hand-written TrustMRR responses for the mapper tests. DOCS_SHAPE mirrors the example on https://trustmrr.com/docs/api/get-startup
// (2026-09); it has not been confirmed against a live key yet — paste one real response here once TRUSTMRR_API_KEY exists.
export const DOCS_SHAPE = {
  data: {
    name: "ShipFast",
    slug: "shipfast",
    icon: "https://cdn.trustmrr.com/icons/shipfast.png",
    description: "The NextJS boilerplate with all you need to build your SaaS, AI tool, or any other web app. From idea to production in 5 minutes.",
    website: "https://shipfa.st",
    country: "TH",
    foundedDate: "2023-09-01T00:00:00.000Z",
    category: "developer-tools",
    paymentProvider: "stripe",
    targetAudience: "b2b",
    revenue: { last30Days: 4250000, mrr: 180000, total: 98000000 },
    customers: 7800,
    activeSubscriptions: 320,
    askingPrice: 50000000,
    profitMarginLast30Days: 92,
    growth30d: 0.12,
    growthMRR30d: 8.5,
    multiple: 0.98,
    rank: 42,
    visitorsLast30Days: 12400,
    googleSearchImpressionsLast30Days: 513015,
    revenuePerVisitor: 3.87,
    domainRating: 58,
    onSale: true,
    firstListedForSaleAt: "2025-11-15T08:30:00.000Z",
    founderMessage: "ShipFast is profitable and simple to operate. I am looking for the right buyer to keep growing it.",
    xHandle: "shipaborad",
    xFollowerCount: 15400,
    isMerchantOfRecord: false,
    startupInsights: {
      valueProposition: "Launch a production-ready SaaS faster with payments, auth, emails, and deployment already wired together.",
      problemSolved: "Founders lose weeks rebuilding the same SaaS boilerplate before they can test an idea.",
      pricingModel: "One-time purchase with tiered licenses",
      targetPersona: "Solo founders and indie hackers launching SaaS products",
      businessType: "B2B",
      teamSize: "2-5",
      fundingStatus: "bootstrapped",
      estimatedUserCount: 7800,
    },
    techStack: [
      { slug: "nextjs", category: "framework" },
      { slug: "mongodb", category: "database" },
      { slug: "tailwindcss", category: "css" },
      { slug: "stripe", category: "payments" },
      { slug: "some-obscure-lib", category: "other" },
    ],
    marketingChannels: [
      { slug: "seo", category: "organic" },
      { slug: "x-twitter", category: "social" },
      { slug: "billboards", category: "offline" },
    ],
    cofounders: [{ xHandle: "marc_louvion", xName: "Marc Lou" }],
  },
};

// Bare object, snake_case keys, comma strings, string arrays, numeric team size, VC wording, mobile flags.
export const SNAKE_BARE = {
  name: "Pocket Budget",
  slug: "pocket-budget",
  logo: "https://cdn.trustmrr.com/icons/pocket-budget.png",
  description: "Envelope budgeting for couples.",
  website_url: "https://pocketbudget.app",
  country_code: "de",
  founded_at: "2021-03-15",
  categories: "fintech, mobile-apps, health-fitness",
  payment_provider: "revenuecat",
  target_audience: "both",
  mrr: 420000,
  revenue: { last_30_days: 500000 },
  asking_price: null,
  tech_stack: "React Native, Expo, Supabase, PostgreSQL, Node.js, Vue.js, Unknownium",
  marketing_channels: ["App Store", "Instagram", "Reddit", { slug: "google-ads", category: "paid" }],
  cofounders: ["@ada", { name: "Grace Hopper", twitter: "https://x.com/grace_h/" }, { x_name: "No Handle" }],
  team_size: 12,
  funding_status: "VC funded (seed)",
  value_proposition: "Budget together without spreadsheets.",
  problem_solved: "Couples fight about money because nobody sees the whole picture.",
  pricing_model: "Free tier + family plan subscription",
};

// Almost nothing useful: the mapper must survive junk values and produce a tiny prefill.
export const SPARSE = { data: { name: "  Tiny  ", slug: "tiny", website: "", icon: "http://insecure.example/icon.png", country: "Narnia", foundedDate: "not a date", category: "saas", techStack: null, marketingChannels: 42, cofounders: [{}], startupInsights: { teamSize: "hundreds", fundingStatus: "unknown" } } };
