// Better Auth — native plugin provider. UserTrack pulls signed aggregate metrics from the @usertrack/better-auth plugin
// installed in the founder's app (POST <baseUrl>/usertrack/metrics). No user records, no PII: counts and timestamps only.
import { EVENTS_PATH, HEADER_NONCE, METRICS_PATH, MIN_PLUGIN_VERSION, PROTOCOL_VERSION, SUPPORTED_PROTOCOL_VERSIONS, signedHeaders, verify, versionAtLeast } from "../lib/betterAuthProtocol";
import { asCount, hostOf, ProviderError, str, type History, type Provider, type ProviderMetrics } from "./types";

export interface BetterAuthConfig {
  // Better Auth base URL of the founder's app, e.g. https://app.example.com/api/auth
  url: string;
  // Integration secret shared with the plugin (ut_int_…). Generated by UserTrack, shown once.
  secret: string;
  secretHash: string;
  secretPrefix: string;
  createdAt: number;
}

interface MetricsBody {
  protocolVersion?: number;
  pluginVersion?: string;
  provider?: string;
  projectId?: string;
  totalUsers?: number;
  newUsers?: { "24h"?: number; "7d"?: number; "30d"?: number };
  daily?: { day: string; newUsers: number }[];
  capabilities?: { exactCounts?: boolean; history?: boolean; anonymousExcluded?: boolean };
}

const TIMEOUT_MS = 15_000;

export function normalizeBaseUrl(raw: string) {
  const trimmed = raw.trim().replace(/\/+$/, "");
  let u: URL;
  try {
    u = new URL(trimmed);
  } catch {
    return { ok: false as const, error: "Enter the Better Auth base URL of your app, e.g. https://app.example.com/api/auth" };
  }
  const local = u.hostname === "localhost" || u.hostname === "127.0.0.1";
  if (u.protocol !== "https:" && !(u.protocol === "http:" && local)) return { ok: false as const, error: "The Better Auth URL must use https://" };
  if (u.search || u.hash) return { ok: false as const, error: "The Better Auth URL must not contain a query string" };
  if (u.pathname === "/" || u.pathname === "") u.pathname = "/api/auth";
  return { ok: true as const, url: u.toString().replace(/\/+$/, "") };
}

export const metricsUrl = (base: string) => `${base}${METRICS_PATH}`;

// Actionable, secret-free messages for every failure mode of the pull.
export function explainStatus(status: number, code: string | undefined, url: string): { message: string; retryable: boolean } {
  const host = hostOf(url) ?? url;
  if (status === 404) return { message: `No UserTrack plugin found at ${host}${METRICS_PATH}. Install @usertrack/better-auth, add userTrack() to your Better Auth plugins and deploy.`, retryable: false };
  if (status === 401 && code === "USERTRACK_STALE_REQUEST") return { message: `${host} rejected the request as stale — the server clock is off by more than 5 minutes.`, retryable: true };
  if (status === 401 && code === "USERTRACK_REPLAY") return { message: `${host} reported a replayed request. Retry in a moment.`, retryable: true };
  if (status === 401 || status === 403) return { message: `${host} rejected the signature. USERTRACK_PROJECT_ID or USERTRACK_SECRET in the app does not match this integration — check the env vars, redeploy, or rotate the secret.`, retryable: false };
  if (status === 429) return { message: `${host} is rate limiting UserTrack (429).`, retryable: true };
  if (status >= 500) return { message: `${host} answered ${status} — the plugin could not count users (database adapter error?).`, retryable: true };
  return { message: `${host} answered ${status}`, retryable: status >= 500 };
}

async function pull(cfg: BetterAuthConfig, projectId: string, request: Record<string, unknown>): Promise<MetricsBody> {
  const body = JSON.stringify({ protocolVersion: PROTOCOL_VERSION, ...request });
  const url = metricsUrl(cfg.url);
  const headers = await signedHeaders(cfg.secret, projectId, { method: "REQUEST", path: METRICS_PATH, body });
  let res: Response;
  try {
    res = await fetch(url, { method: "POST", headers: { "content-type": "application/json", accept: "application/json", "user-agent": "UserTrack/1.0 (+https://usertrack.dev)", ...headers }, body, signal: AbortSignal.timeout(TIMEOUT_MS) });
  } catch (e) {
    throw new ProviderError(`Could not reach ${hostOf(url) ?? url}: ${(e as Error).name === "TimeoutError" ? "timed out" : "connection failed"}. Is the app deployed and reachable over HTTPS?`, true);
  }
  const text = await res.text();
  if (!res.ok) {
    let code: string | undefined;
    try {
      code = (JSON.parse(text) as { code?: string }).code;
    } catch {
      /* not json */
    }
    const { message, retryable } = explainStatus(res.status, code, url);
    throw new ProviderError(message, retryable);
  }
  const sig = await verify(cfg.secret, res.headers, { method: "RESPONSE", path: METRICS_PATH, body: text }, { expectedNonce: headers[HEADER_NONCE] });
  if (!sig.ok) throw new ProviderError(`Response from ${hostOf(url) ?? url} failed signature verification (${sig.reason}). Check that the deployed USERTRACK_SECRET matches.`, false);
  let parsed: MetricsBody;
  try {
    parsed = JSON.parse(text) as MetricsBody;
  } catch {
    throw new ProviderError("Plugin response is not valid JSON", false);
  }
  if (!SUPPORTED_PROTOCOL_VERSIONS.includes(Number(parsed.protocolVersion))) throw new ProviderError(`Unsupported plugin protocol version ${parsed.protocolVersion ?? "?"} — update @usertrack/better-auth.`, false);
  if (typeof parsed.pluginVersion === "string" && !versionAtLeast(parsed.pluginVersion, MIN_PLUGIN_VERSION)) throw new ProviderError(`@usertrack/better-auth ${parsed.pluginVersion} is outdated; ${MIN_PLUGIN_VERSION} or newer is required.`, false);
  if (parsed.projectId && parsed.projectId !== projectId) throw new ProviderError("The plugin is configured for a different UserTrack project id.", false);
  return parsed;
}

// The plugin identifies the integration by the UserTrack project id; the provider needs it to sign.
// Convex providers only receive the config, so it is carried inside the config at creation time.
export type BetterAuthStoredConfig = BetterAuthConfig & { projectId: string };

export const betterAuth: Provider<BetterAuthStoredConfig> = {
  kind: "better_auth",
  label: "Better Auth",
  roles: ["users"],
  capabilities: ["totalUsers", "usersInRange", "history"],
  validate(config) {
    const url = normalizeBaseUrl(str(config, "url"));
    if (!url.ok) return url;
    const secret = str(config, "secret");
    const projectId = str(config, "projectId");
    if (!secret || !projectId) return { ok: false, error: "Better Auth integrations are created from the UserTrack dashboard or usertrack_create_integration, which generate the secret." };
    return { ok: true, config: { url: url.url, secret, projectId, secretHash: str(config, "secretHash"), secretPrefix: str(config, "secretPrefix") || secret.slice(0, 11), createdAt: Number((config as BetterAuthConfig).createdAt) || Date.now() } };
  },
  // The response is signed with a secret only the founder's deployment holds: verified regardless of hostname.
  trust: () => "verified",
  async fetch(cfg) {
    const m = await pull(cfg, cfg.projectId, {});
    const out: ProviderMetrics = {
      totalUsers: asCount(m.totalUsers, "totalUsers"),
      newUsers24h: asCount(m.newUsers?.["24h"], "newUsers.24h"),
      newUsers7d: asCount(m.newUsers?.["7d"], "newUsers.7d"),
      newUsers30d: asCount(m.newUsers?.["30d"], "newUsers.30d"),
      sourceVersion: typeof m.pluginVersion === "string" ? m.pluginVersion.slice(0, 32) : undefined,
      protocolVersion: Number(m.protocolVersion) || undefined,
    };
    return out;
  },
  async fetchHistory(cfg, _role, days): Promise<History | null> {
    const m = await pull(cfg, cfg.projectId, { days: Math.min(90, Math.max(1, days)) });
    if (!Array.isArray(m.daily)) return null;
    return { metric: "newUsers", points: m.daily.map((d) => ({ day: String(d.day), value: asCount(d.newUsers, `daily.${d.day}`) })) };
  },
  publicConfig: (cfg) => ({ url: cfg.url, secret: `${cfg.secretPrefix}…`, events: EVENTS_PATH }),
};
