// Native SDK provider: UserTrack pulls signed aggregate metrics from a client that speaks the native protocol —
// @usertrack/better-auth or @usertrack/node (Prisma, Drizzle, Convex, Auth.js, custom). No user records, no PII.
import { EVENTS_PATH, HEADER_NONCE, METRICS_PATH, MIN_CLIENT_VERSION, NATIVE_PACKAGE, NATIVE_SOURCE_LABEL, type NativeSource, normalizeSource, PROTOCOL_VERSION, SUPPORTED_PROTOCOL_VERSIONS, signedHeaders, verify, versionAtLeast } from "../lib/nativeProtocol";
import { parseMode } from "./conversion";
import { parseIdentities } from "./endpoint";
import { checkPublicHttpsUrl } from "../lib/ssrf";
import { asCount, capabilitiesFromList, hostOf, hostnameOf, isRedirect, ProviderError, REDIRECT_ERROR, str, type History, type Provider, type ProviderCapabilities, type ProviderMetrics, type Role } from "./types";

// What the last successful pull reported; patched into the config by the sync engine (metrics.reported).
export interface ReportedCapabilities { roles: Role[]; history: boolean; identity: boolean; exactCounts: boolean }

export interface NativeConfig {
  // Base URL the client is mounted on: <baseURL>/api/auth for Better Auth, https://app.example.com/api/usertrack otherwise.
  url: string;
  source: NativeSource;
  // Integration secret shared with the client (ut_int_…). Generated by UserTrack, shown once.
  secret: string;
  secretHash: string;
  secretPrefix: string;
  createdAt: number;
  reported?: ReportedCapabilities;
}
// The client identifies the integration by the UserTrack project id; providers only receive the config, so it is carried inside.
export type NativeStoredConfig = NativeConfig & { projectId: string };

interface Windows { "24h"?: number; "7d"?: number; "30d"?: number }
interface MetricsBody {
  protocolVersion?: number;
  clientVersion?: string;
  pluginVersion?: string;
  source?: string;
  provider?: string;
  projectId?: string;
  totalUsers?: number;
  newUsers?: Windows;
  daily?: { day: string; newUsers: number }[];
  users?: { totalUsers?: number; newUsers?: Windows; daily?: { day: string; newUsers: number }[] };
  activation?: { activatedUsers?: number; activated24h?: number; activated7d?: number; activated30d?: number; daily?: { day: string; activatedUsers: number }[] };
  conversion?: { convertedUsers?: number; newConverted24h?: number; newConverted7d?: number; newConverted30d?: number; trialUsers?: number; newTrials7d?: number; newTrials30d?: number; mode?: string };
  identities?: Record<string, unknown>;
  capabilities?: { exactCounts?: boolean; history?: boolean; anonymousExcluded?: boolean; roles?: string[] };
}

const TIMEOUT_MS = 15_000;
// Protocol v1 caps `days` at 90 (packages/protocol MAX_HISTORY_DAYS), so native history is bounded to that window.
export const NATIVE_HISTORY_DAYS = 90;
const ROLES: Role[] = ["users", "activation", "conversion"];

export const defaultBasePath = (source: NativeSource) => (source === "better-auth" ? "/api/auth" : "/api/usertrack");
export const sourceLabel = (source: NativeSource | undefined) => NATIVE_SOURCE_LABEL[normalizeSource(source)];
// Rows created before migrations:nativeV1 have no `source`: they are Better Auth plugins.
const sourceOf = (cfg: { source?: NativeSource }) => cfg.source ?? "better-auth";

export function normalizeBaseUrl(raw: string, source: NativeSource = "better-auth") {
  const trimmed = raw.trim().replace(/\/+$/, "");
  const what = source === "better-auth" ? "Better Auth base URL" : "base URL of the UserTrack handler";
  let u: URL;
  try {
    u = new URL(trimmed);
  } catch {
    return { ok: false as const, error: `Enter the ${what} of your app, e.g. https://app.example.com${defaultBasePath(source)}` };
  }
  const pub = checkPublicHttpsUrl(trimmed, { what: `The ${what}`, anyPort: true });
  if (!pub.ok) return { ok: false as const, error: pub.reason };
  if (u.search || u.hash) return { ok: false as const, error: `The ${what} must not contain a query string` };
  if (u.pathname === "/" || u.pathname === "") u.pathname = defaultBasePath(source);
  return { ok: true as const, url: u.toString().replace(/\/+$/, "") };
}

// Better Auth mounts the plugin endpoint under its own base path; @usertrack/node handlers are mounted at <base>/metrics.
export const metricsUrl = (base: string, source: NativeSource = "better-auth") => (source === "better-auth" ? `${base}${METRICS_PATH}` : `${base}/metrics`);

// Actionable, secret-free messages for every failure mode of the pull.
export function explainStatus(status: number, code: string | undefined, url: string, source: NativeSource = "better-auth"): { message: string; retryable: boolean } {
  const host = hostOf(url) ?? url;
  const pkg = NATIVE_PACKAGE[source];
  if (status === 404) return { message: source === "better-auth" ? `No UserTrack plugin found at ${host}${METRICS_PATH}. Install ${pkg}, add userTrack() to your Better Auth plugins and deploy.` : `No UserTrack handler found at ${url}/metrics. Install ${pkg}, mount createUserTrackHandler() at that path and deploy.`, retryable: false };
  if (status === 401 && code === "USERTRACK_STALE_REQUEST") return { message: `${host} rejected the request as stale — the server clock is off by more than 5 minutes.`, retryable: true };
  if (status === 401 && code === "USERTRACK_REPLAY") return { message: `${host} reported a replayed request. Retry in a moment.`, retryable: true };
  if (status === 401 || status === 403) return { message: `${host} rejected the signature. USERTRACK_PROJECT_ID or USERTRACK_SECRET in the app does not match this integration — check the env vars, redeploy, or rotate the secret.`, retryable: false };
  if (status >= 300 && status < 400) return { message: `${host} redirected the request (${status}) — ${REDIRECT_ERROR.toLowerCase()}.`, retryable: false };
  if (status === 429) return { message: `${host} is rate limiting UserTrack (429).`, retryable: true };
  if (status === 502 || status === 503 || status === 504) return { message: `${host} is not reachable right now (${status}) — is the app deployed and running?`, retryable: true };
  if (status >= 500) return { message: `${host} answered ${status} — ${pkg} could not count users (data source error?).`, retryable: true };
  return { message: `${host} answered ${status}`, retryable: status >= 500 };
}

async function pull(cfg: NativeStoredConfig, request: Record<string, unknown>): Promise<MetricsBody> {
  const body = JSON.stringify({ protocolVersion: PROTOCOL_VERSION, ...request });
  const source = sourceOf(cfg);
  const url = metricsUrl(cfg.url, source);
  const headers = await signedHeaders(cfg.secret, cfg.projectId, { method: "REQUEST", path: METRICS_PATH, body });
  let res: Response;
  try {
    res = await fetch(url, { method: "POST", headers: { "content-type": "application/json", accept: "application/json", "user-agent": "UserTrack/1.0 (+https://usertrack.dev)", ...headers }, body, redirect: "manual", signal: AbortSignal.timeout(TIMEOUT_MS) });
  } catch (e) {
    throw new ProviderError(`Could not reach ${hostOf(url) ?? url}: ${(e as Error).name === "TimeoutError" ? "timed out" : "connection failed"}. Is the app deployed and reachable over HTTPS?`, true);
  }
  if (isRedirect(res)) throw new ProviderError(explainStatus(res.status || 302, undefined, cfg.url, source).message, false);
  const text = await res.text();
  if (!res.ok) {
    let code: string | undefined;
    try {
      code = (JSON.parse(text) as { code?: string }).code;
    } catch {
      /* not json */
    }
    const { message, retryable } = explainStatus(res.status, code, cfg.url, source);
    throw new ProviderError(message, retryable);
  }
  const sig = await verify(cfg.secret, res.headers, { method: "RESPONSE", path: METRICS_PATH, body: text }, { expectedNonce: headers[HEADER_NONCE] });
  if (!sig.ok) throw new ProviderError(`Response from ${hostOf(url) ?? url} failed signature verification (${sig.reason}). Check that the deployed USERTRACK_SECRET matches.`, false);
  let parsed: MetricsBody;
  try {
    parsed = JSON.parse(text) as MetricsBody;
  } catch {
    throw new ProviderError("Client response is not valid JSON", false);
  }
  const pkg = NATIVE_PACKAGE[source];
  if (!SUPPORTED_PROTOCOL_VERSIONS.includes(Number(parsed.protocolVersion))) throw new ProviderError(`Unsupported protocol version ${parsed.protocolVersion ?? "?"} — update ${pkg}.`, false);
  const version = clientVersion(parsed);
  if (version && !versionAtLeast(version, MIN_CLIENT_VERSION[source])) throw new ProviderError(`${pkg} ${version} is outdated; ${MIN_CLIENT_VERSION[source]} or newer is required.`, false);
  if (parsed.projectId && parsed.projectId !== cfg.projectId) throw new ProviderError("The client is configured for a different UserTrack project id.", false);
  return parsed;
}

const clientVersion = (m: MetricsBody) => (typeof m.clientVersion === "string" ? m.clientVersion : typeof m.pluginVersion === "string" ? m.pluginVersion : undefined);
// The 0.1.x Better Auth plugin reports users at the top level; newer clients nest them under `users`.
const usersBlock = (m: MetricsBody) => m.users ?? (m.totalUsers !== undefined ? { totalUsers: m.totalUsers, newUsers: m.newUsers, daily: m.daily } : undefined);
const reportedRoles = (m: MetricsBody): Role[] => {
  const roles = new Set<Role>();
  if (usersBlock(m)) roles.add("users");
  if (m.activation) roles.add("activation");
  if (m.conversion) roles.add("conversion");
  return ROLES.filter((r) => roles.has(r));
};
const opt = (v: unknown, what: string) => (v === undefined || v === null ? undefined : asCount(v, what));

export function parseMetrics(m: MetricsBody, role: Role): ProviderMetrics {
  const out: ProviderMetrics = {
    sourceVersion: clientVersion(m)?.slice(0, 32),
    protocolVersion: Number(m.protocolVersion) || undefined,
    reported: { roles: reportedRoles(m), history: m.capabilities?.history !== false, identity: Boolean(m.identities), exactCounts: m.capabilities?.exactCounts !== false },
  };
  if (role === "users") {
    const u = usersBlock(m);
    if (!u) throw new ProviderError("The client did not report registered users (users.totalUsers)", false);
    out.totalUsers = asCount(u.totalUsers, "users.totalUsers");
    out.newUsers24h = opt(u.newUsers?.["24h"], "users.newUsers.24h");
    out.newUsers7d = opt(u.newUsers?.["7d"], "users.newUsers.7d");
    out.newUsers30d = opt(u.newUsers?.["30d"], "users.newUsers.30d");
  } else if (role === "activation") {
    const a = m.activation;
    if (!a) throw new ProviderError("The client does not report activation — add an activation source to the handler", false);
    out.activatedUsers = asCount(a.activatedUsers, "activation.activatedUsers");
    out.activated24h = opt(a.activated24h, "activation.activated24h");
    out.activated7d = opt(a.activated7d, "activation.activated7d");
    out.activated30d = opt(a.activated30d, "activation.activated30d");
  } else if (role === "conversion") {
    const c = m.conversion;
    if (!c) throw new ProviderError("The client does not report conversion — add a conversion source to the handler", false);
    out.convertedUsers = asCount(c.convertedUsers, "conversion.convertedUsers");
    out.newConverted24h = opt(c.newConverted24h, "conversion.newConverted24h");
    out.newConverted7d = opt(c.newConverted7d, "conversion.newConverted7d");
    out.newConverted30d = opt(c.newConverted30d, "conversion.newConverted30d");
    out.trialUsers = opt(c.trialUsers, "conversion.trialUsers");
    out.newTrials7d = opt(c.newTrials7d, "conversion.newTrials7d");
    out.newTrials30d = opt(c.newTrials30d, "conversion.newTrials30d");
    out.conversionMode = parseMode(c as Record<string, unknown>) ?? "active_paid";
  } else throw new ProviderError("Native sources do not report traffic", false);
  if (m.identities) out.identities = parseIdentities(m as Record<string, unknown>, role);
  return out;
}

export const native: Provider<NativeStoredConfig> = {
  kind: "native",
  label: "My app (SDK)",
  roles: ROLES,
  capabilities: ["totalUsers", "usersInRange", "history", "activation", "trial", "converted", "identity"],
  validate(config) {
    const source = normalizeSource(str(config, "source") || "better-auth");
    const url = normalizeBaseUrl(str(config, "url"), source);
    if (!url.ok) return url;
    const secret = str(config, "secret");
    const projectId = str(config, "projectId");
    if (!secret || !projectId) return { ok: false, error: "Native integrations are created from the UserTrack dashboard or usertrack_create_integration, which generate the secret." };
    const c = config as Partial<NativeConfig>;
    return { ok: true, config: { url: url.url, source, secret, projectId, secretHash: str(config, "secretHash"), secretPrefix: str(config, "secretPrefix") || secret.slice(0, 11), createdAt: Number(c.createdAt) || Date.now(), ...(c.reported ? { reported: c.reported } : {}) } };
  },
  // The response is signed with a secret only the founder's deployment holds: verified regardless of hostname.
  trust: () => "verified",
  async fetch(cfg, role) {
    return parseMetrics(await pull(cfg, {}), role);
  },
  historyLimit: () => ({ reach: "bounded", maxDays: NATIVE_HISTORY_DAYS }),
  async fetchHistory(cfg, role, days): Promise<History | null> {
    if (role === "conversion") return null;
    const m = await pull(cfg, { days: Math.min(NATIVE_HISTORY_DAYS, Math.max(1, days)) });
    if (role === "activation") {
      const daily = m.activation?.daily;
      if (!Array.isArray(daily)) return null;
      return { metric: "activatedUsers", points: daily.map((d) => ({ day: String(d.day), value: asCount(d.activatedUsers, `activation.daily.${d.day}`) })) };
    }
    const daily = usersBlock(m)?.daily;
    if (!Array.isArray(daily)) return null;
    return { metric: "newUsers", points: daily.map((d) => ({ day: String(d.day), value: asCount(d.newUsers, `daily.${d.day}`) })) };
  },
  // Capabilities reflect what the last pull actually returned; before the first pull, the static list.
  describe(cfg, role): ProviderCapabilities {
    const base = capabilitiesFromList(this.capabilities, role);
    const r = cfg.reported;
    if (!r) return { ...base, identity: false };
    return { ...base, historicalUsers: base.historicalUsers && r.history, identity: r.identity };
  },
  publicConfig: (cfg) => ({ url: cfg.url, source: sourceOf(cfg), secret: `${cfg.secretPrefix}…`, events: EVENTS_PATH }),
  hosts: (cfg) => [hostnameOf(cfg.url)],
  labelFor: (cfg) => (sourceOf(cfg) === "better-auth" ? "Better Auth" : sourceOf(cfg) === "custom" ? "UserTrack SDK" : `${sourceLabel(sourceOf(cfg))} (UserTrack SDK)`),
};
